### ISSUE TITLE
[Request] Is there a chance to set the component Width?

### ISSUE THREAD

**Issue by finalquest** [brentvatne/react-native-scrollable-tab-view#10]
Hi.
First of all, an awesome work.

I was wondering if you have considered using a specific width set in the component instead of using the deviceWidth?
This way the component could be used in some places that not respect the full device width

Regards

**Comment by brentvatne** [comment]
Sure! If you want to submit a PR to make it default to the deviceWidth but use a given width if it is passed in, that would be cool!
