### ISSUE TITLE
miss the key props

### ISSUE THREAD

**Issue by kazaff** [brentvatne/react-native-scrollable-tab-view#100]
must add "key" props in map:

```javascript
...
{this.props.children.map((child, index) => {
           return <View key={index} style={{width: deviceWidth}}>{child}</View>
})}
...
```

about in [here](https://github.com/brentvatne/react-native-scrollable-tab-view/blob/master/index.js#L113)

**Comment by kazaff** [comment]
by the way, the custom style props is not work, i think the owner will fix them in couple of day

**Comment by skv-headless** [comment]
hello @kazaff . Now there is key property. Could you please explain your note about custom style?

**Comment by kazaff** [comment]
@skv-headless  like:  tabBarUnderlineColor, tabBarBackgroundColor, tabBarActiveTextColor, tabBarInactiveTextColor...

**Comment by kazaff** [comment]
i find that , when i re-install this lib, the code version is not latest, why? 
```
npm install react-native-scrollable-tab-view@latest --save
```

**Comment by skv-headless** [comment]
last version have not published yet to npm
