### ISSUE TITLE
InitialPage prop does nothing on android

### ISSUE THREAD

**Issue by mikemonteith** [brentvatne/react-native-scrollable-tab-view#102]
It seems that the initialPage prop does nothing (tested on android only)

**Comment by mikemonteith** [comment]
Seems related to this https://github.com/facebook/react-native/issues/3653

**Comment by skv-headless** [comment]
I guess it fixed in 0.16. First we need to update example.

**Comment by mikemonteith** [comment]
I have opened a pull request, updating the react version and fixing the issue #102 are both in one PR but merged as separate branches.
Let me know if you want me to create two separate PRs with a rebase in between.
