### ISSUE TITLE
the page under the scrollviewtab is not rendered until the tab label has been clicked on it

### ISSUE THREAD

**Issue by rashmi-chachan** [brentvatne/react-native-scrollable-tab-view#104]
'use strict';
var React = require('react-native');
var {
    StyleSheet,
    Component,
    View, ListView,
    Text, TextInput, Image,
    TouchableHighlight,
    TouchableOpacity,
    TouchableNativeFeedback,
    TouchableWithoutFeedback,
    ScrollView,
    Animated,
    Easing,
} = React;
var Dimensions = require('Dimensions');
var {
    width, height
} = Dimensions.get('window');
var ScrollableTabView = require('react-native-scrollable-tab-view');

var ProfileTabBar = React.createClass({
    gotoLikePage: function() {
        this.props.goToPage(0);
    },
    gotoCollectionPage: function() {
        this.props.goToPage(1);
    },
    gotoMyAccountsPage: function() {
        this.props.goToPage(2);
    },
    renderProTabOption: function() {
        var x = this.props.activeTab;
        
    return (
      <View>
        <View style={styles.sectionTabs}>
         <TouchableHighlight key={0}  onPress={()=>this.gotoLikePage()} style={[styles.tabWrapr,]} underlayColor ='#ffffff'>
              <View style={[styles.tabWrapr]}>
                  <Text style={[styles.fontcmmn,{color: x==0 ? '#5AD8BE':'#686D78'}]}>Likes </Text>
                  <Text style={styles.tabNo}>21</Text>
              </View>
         </TouchableHighlight>
         <TouchableHighlight key={1} onPress={()=>this.gotoCollectionPage()} style={[styles.tabWrapr,,styles.tabMiddle]} underlayColor ='#ffffff'>
              <View style={[styles.tabWrapr,styles.tabMiddle]}>
                  <Text style={[styles.fontcmmn,{color: x==1 ? '#5AD8BE':'#686D78'}]}>Collections </Text>
                  <Text style={[styles.fontcmmn,styles.tabNo]}>2</Text>
              </View>
         </TouchableHighlight>
         <TouchableHighlight key={2} onPress={()=>this.gotoMyAccountsPage()}  style={styles.tabWrapr} underlayColor ='#ffffff'>
              <View style={styles.tabWrapr}>
                  <Text style={[styles.fontcmmn,{color: x==2 ? '#5AD8BE':'#686D78'}]}>My Account</Text>
              </View>                    
         </TouchableHighlight>
        </View>
      </View>    
    );
  },
    render:function(){
        return(
            <View style={{height:45}}>
                {this.renderProTabOption()}
            </View>
            );
    },
});

var ProfilePage = React.createClass({
    horScrollViewInstance: {
        scrollTo: () => {}
    },
    getDefaultProps: function() {
        return {
            pageToLoad: ''
        }
    },
    getInitialState: function() {
        var layoutStyle = StyleSheet.create({
            sectionWrapr: {}
        });
        return {
            profileJson: [],
            layoutStyle: layoutStyle,
            // pageToLoad: "collectionPage",
            moveY: new Animated.ValueXY({
                x: 0,
                y: 0
            }),
        }
    },
    setLayout: function(event) {
        var layout = event.nativeEvent.layout;
        var layoutStyle = StyleSheet.create({
            sectionWrapr: {
                width: layout.width,
                alignItems: 'stretch',
            },
        });
        this.setState({
            layoutStyle: layoutStyle
        });
    },
    
    // componentWillReceiveProps: function(nextProps) {
    //     if (this.props.pageToLoad != nextProps.pageToLoad && nextProps.pageToLoad == 'profilePage') {
    //         this.gotoCollectionPage();
    //     }
    // },
    scaleAnim: function(shudScale) {
        if (shudScale) {
            Animated.timing(
                this.state.moveY, {
                    toValue: 10,
                    easing: Easing.inOut(Easing.ease),
                    duration: 800,
                }).start();
        }
    },
    move: {
        x: 0,
        y: 0
    },
    startScroll: 0,
    drag: {
        x: 0,
        y: 0
    },
    scale: 0,
    _verticalScrollStart: function(event) {
        console.log("start");
        console.log(height);
        this.myscroll = true;
        this.drag = {
            x: 0,
            y: event.nativeEvent.pageY
        }
        this.startScroll = event.nativeEvent.pageY;
        return true;
    },
    _verticalScrollMove: function(event) {
        this.move.y = this.move.y + (event.nativeEvent.pageY - this.drag.y);
        if ((this.move.y <= 0) && (this.move.y >= -340)) {
            console.log("this.move.y came in if " + this.move.y);
            this.state.moveY.setValue({
                x: 0,
                y: this.move.y
            });
            this.drag.y = event.nativeEvent.pageY;
            this.scale = this.state.moveY.y;
        }
        console.log("this.move.y " + this.move.y);
    },
    _verticalScrollEnd: function(event: Object) {},
    render: function() {
        var borderStyle = {
            // borderWidth: 1,
            // borderStyle: 'dashed',
            // borderColor: '#A8ACB1',
        }
        return (
            <View style={[{flex:1}]}> 
        <View style={[styles.sectionWrapr]}
          onStartShouldSetResponder={(event)=>this._verticalScrollStart(event)}
          onMoveShouldSetResponder={()=> true}
          onResponderMove={(event)=>this._verticalScrollMove(event)}
          onResponderRelease={this._verticalScrollEnd}
          onResponderTerminate = {this._verticalScrollEnd}
          onStartShouldSetResponderCapture={()=> false}>      
          <Animated.View style={[{width:width,transform: this.state.moveY.getTranslateTransform()}]}>   
            <View style={[styles.sectionHeader]}>
               <View>
                   <View style={styles.coverPicWrapr}>
                        <Image style={styles.coverPic} source={{uri: 'coverpic'}}/>
                   </View>
               </View>
               <Animated.View style={[styles.profilePicWrapr,
                {transform:[{
                  scale: this.state.moveY.y.interpolate({
                  inputRange: [-100, 0],
                  outputRange: [0.7, 1],
                })
               }] }]} >
                   <View style={[styles.proPicIn]}>
                     <View style={styles.proPic}>
                       <View style={styles.camerapicwrapr}><Image style={styles.proPicCamera} source={{uri: 'camera'}}/></View>
                       <Text style={styles.proPicAdd}>ADD</Text>
                     </View>
                   </View>
               </Animated.View>
               <View style={styles.sectionHeaderDetails}>
                 <View style={styles.sectionHeaderDetailsDisplay}>
                    <View style={styles.proNameWrapr}><Text style={styles.proName}>Rashmi Chachan</Text></View>
                    <View style={styles.addBiorWrapr}><Text style={styles.addBio}>Add Bio</Text></View>
                    <View style={styles.followWrapr}>
                        <View style={[styles.followxxWrapr,styles.followingWrapr]}><Text style={styles.followNo}>0 </Text><Text style={styles.follow}>Following</Text></View>
                        <View style={styles.followxxWrapr}><Text style={styles.followNo}>0 </Text><Text style={styles.follow}>Followers</Text></View>
                    </View>
                 </View>
                 <View style={styles.editWraprFake}>
                     <View style={styles.editWrapr}>
                            <Image style={styles.edit} source={{uri: 'edit'}}/>
                     </View>
                 </View>
               </View>                          
            </View>
            <View style={styles.sectionBody}>
              <View style={[styles.sectionContent]}>
                <ScrollableTabView initialPage={1} renderTabBar={() => <ProfileTabBar />}> 
                    <View style={{flex:1}}><ScrollView showsVerticalScrollIndicator = {true}>
                      <View style={[styles.likes]}> 
                       <View style={styles.columnwrap}>
                            <View style={styles.rowwrap}>
                              <View style={styles.productwholewrapr}>
                                <TouchableWithoutFeedback
                                  onPress={this.gotoProductDetails}>
                                  <View style={styles.productwrap}>
                                      <View style={styles.Displaypic}>
                                          <Image style={styles.Displaypicimage} source={{uri: 'displayimage2'}} />
                                      </View>
                                      <View style={styles.textwrap}>
                                          <View style={[styles.rates]}>
                                            <View style={[styles.pricesLike]}>
                                              <View><Text style={styles.brandName}>GreyStone</Text></View>
                                              <View><Text style={styles.priceNow}>Rs 300</Text></View>
                                            </View>
                                            <View style={styles.threedotspicwrapr}>
                                              <View style={styles.threedotspic}>
                                                <Image style={styles.threedots} source={{uri: 'threedots'}} />
                                              </View>
                                            </View>
                                          </View>  
                                      </View>
                                  </View>    
                                </TouchableWithoutFeedback>
                              </View>    
                              <View style={styles.productwholewrapr}>
                                <TouchableWithoutFeedback
                                  onPress={this.gotoProductDetails}>
                                  <View style={styles.productwrap}>
                                      <View style={styles.Displaypic}>
                                          <Image style={styles.Displaypicimage} source={{uri: 'displayimage2'}} />
                                      </View>
                                      <View style={styles.textwrap}>
                                          <View style={[styles.rates]}>
                                            <View style={[styles.pricesLike]}>
                                              <View><Text style={styles.brandName}>GreyStone</Text></View>
                                              <View><Text style={styles.priceNow}>Rs 300</Text></View>
                                            </View>
                                            <View style={styles.threedotspicwrapr}>
                                              <View style={styles.threedotspic}>
                                                <Image style={styles.threedots} source={{uri: 'threedots'}} />
                                              </View>
                                            </View>
                                          </View>  
                                      </View>
                                  </View>
                                </TouchableWithoutFeedback> 
                              </View>      
                            </View> 
                        </View>    
                      </View>
                    </ScrollView></View>
                    <View style={{flex:1}}><ScrollView showsVerticalScrollIndicator = {true}>
                      <View style={[styles.collections,styles.tabSection]}>
                        <View style={styles.collectionsDivisions}>  
                          <View style={[styles.wishlist,styles.division]}>
                            <View style={styles.subdivision}>
                              <Image style={styles.wishlistpic} source={{uri: 'wishlist'}}/>
                            </View>
                            <View style={styles.subdivisionBlk}>
                                <Text style={[styles.fontcmmn,styles.subdivisionTitle]}>My Wishlist</Text>
                                <Image style={styles.lock} source={{uri: 'lock'}}/>
                            </View>
                          </View>
                          <View style={[styles.itemsOwn,styles.division]}>
                            <View style={styles.subdivision}>
                              <Image style={styles.itemsiownpic} source={{uri: 'itemsiown'}}/>
                            </View>
                            <View style={styles.subdivisionBlk}>
                                <Text style={[styles.fontcmmn,styles.subdivisionTitle]}>Items I own</Text>
                                <Image style={styles.lock} source={{uri: 'lock'}}/>
                            </View>
                          </View>
                        </View>
                      <View style={[styles.createNewDivision,this.props.style, borderStyle]}>                                       
                        <View style={[styles.createNew]}>
                          <View style={styles.createNewCircle}>
                              <Text style={styles.createNewPlus}> {'+'}</Text>
                          </View>
                          <Text style={[styles.fontcmmn,styles.newDiv]}>Create New</Text>
                        </View>
                      </View>
                      </View>
                    </ScrollView></View> 
                    <View style={{flex:1}}><ScrollView showsVerticalScrollIndicator = {true}>
                      <View style={[styles.myAccounts,styles.tabSection]}>
                      <View style={[styles.section1,styles.myaccsec]}>
                         <View style={styles.styleaccwrapr}><Text style={styles.styleacc}>My Style Forum</Text></View>
                      </View> 
                      <View style={[styles.section2,styles.myaccsec]}>
                         <View style={styles.styleaccwrapr}><Text style={styles.styleacc}>My Orders</Text></View>
                         <View style={styles.styleaccwrapr}><Text style={styles.styleacc}>Handpicked for you</Text></View>
                         <View style={styles.styleaccwrapr}><Text style={styles.styleacc}>Wishlist</Text></View>
                      </View>
                      <View style={[styles.section3,styles.myaccsec]}>
                         <View style={styles.styleaccwrapr}><Text style={styles.styleacc}>Saved Cards</Text></View>
                         <View style={styles.styleaccwrapr}><Text style={styles.styleacc}>Coupons</Text></View>
                         <View style={styles.styleaccwrapr}><Text style={styles.styleacc}>Cashback</Text></View>
                         <View style={styles.styleaccwrapr}><Text style={styles.styleacc}>Myntra Points</Text></View>
                         <View style={styles.styleaccwrapr}><Text style={styles.styleacc}>My Addresses</Text></View>
                      </View>
                      <View style={[styles.section4,styles.myaccsec]}>
                         <View style={styles.styleaccwrapr}><Text style={styles.styleacc}>Notifications</Text></View>
                      </View> 
                      </View>
                    </ScrollView></View>  
                </ScrollableTabView> 
              </View>      
            </View> 
          </Animated.View>
        </View>
      </View>
        );
    },
});
var styles = StyleSheet.create({
    sectionWrapr: {
        width: width,
        flex: 1,
    },
    sectionHeader: {
        backgroundColor: '#ffffff',
    },
    coverPicWrapr: {
        flex: 1,
        alignItems: 'stretch',
        height: 120,
    },
    coverPic: {
        flex: 1
    },
    profilePicWrapr: {
        position: 'absolute',
        left: 150,
        top: 65,
        padding: 2,
        backgroundColor: '#ffffff',
    },
    proPicIn: {
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: '#DADBDD',
        backgroundColor: '#ffffff',
    },
    proPic: {
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#ffffff',
        padding: 15,
        paddingBottom: 5,
    },
    camerapicwrapr: {
        alignItems: 'stretch',
        flex: 1,
    },
    proPicCamera: {
        flex: 1,
        width: 30,
        height: 25,
    },
    proPicAdd: {
        color: '#B6B9BE',
        fontSize: 13,
        textAlign: 'center',
    },
    sectionHeaderDetails: {
        // flexDirection: 'row',
    },
    sectionHeaderDetailsDisplay: {
        alignItems: 'center',
    },
    proNameWrapr: {
        marginTop: 20,
    },
    proName: {
        color: '#535864',
        fontSize: 15,
        fontWeight: 'bold',
    },
    addBiorWrapr: {
        margin: 5,
    },
    addBio: {
        color: '#B0B2B8',
        fontSize: 13,
        fontStyle: 'italic',
    },
    followWrapr: {
        flexDirection: 'row',
        padding: 10,
    },
    followxxWrapr: {
        flex: 1,
        flexDirection: 'row',
        paddingHorizontal: 5,
    },
    followingWrapr: {
        borderRightWidth: 1,
        borderStyle: 'solid',
        borderColor: '#E2E3E5',
    },
    follow: {
        color: '#9598A0',
        fontSize: 13,
    },
    followNo: {
        color: '#747983',
        fontWeight: 'bold',
    },
    editWraprFake: {
        // alignItems : 'flex-end',
        // justifyContent : 'flex-start',
        position: 'absolute',
        // left: 350,
        right: 10,
        top: 20,
        borderWidth: 1,
        borderRadius: 2,
        borderStyle: 'solid',
        borderColor: '#E2E3E5',
        padding: 5,
    },
    editWrapr: {
        flex: 1,
        alignItems: 'stretch',
    },
    edit: {
        flex: 1,
        width: 15,
        height: 15,
    },
    sectionBody: {
      flex:1,
    },
    sectionTabs: {
        flexDirection: 'row',
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderStyle: 'solid',
        borderColor: '#E2E3E5',
        paddingVertical: 10,
        backgroundColor: '#ffffff'
    },
    tabWrapr: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
    },
    fontcmmn: {
        color: '#686D78',
        fontWeight: 'bold',
    },
    tabNo: {
        color: '#A9ADB2',
        fontWeight: 'bold',
        lineHeight: 20,
    },
    tabActive: {
        color: '#5AD8BE',
        fontWeight: 'bold',
    },
    tabMiddle: {
        borderLeftWidth: 1,
        borderRightWidth: 1,
        borderStyle: 'solid',
        borderColor: '#E2E3E5',
    },
    sectionContent: {
        backgroundColor: '#F5F5F6',
        flex: 1,
        flexDirection:'row',
        height:height,
    },
    tabSection: {
        flex: 1,
        width: width,
        padding: 10,
    },
    likes: {
        backgroundColor: '#F5F5F6',
        flex: 1,
        width: width,
        paddingLeft: 10,
        paddingVertical:10,
    },
    collections: {},
    myAccounts: {
        backgroundColor: '#F5F5F6',
    },
    collectionsDivisions: {
        flexDirection: 'row',
    },
    division: {
        flex: 1,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: '#E3E4E5',
    },
    subdivision: {
        height: 200,
        flex: 1,
    },
    wishlistpic: {
        alignItems: 'stretch',
        flex: 1,
    },
    itemsiownpic: {
        alignItems: 'stretch',
        flex: 1,
    },
    wishlist: {
        marginRight: 10,
    },
    subdivisionBlk: {
        padding: 10,
        borderTopWidth: 1,
        borderStyle: 'solid',
        borderColor: '#E3E4E5',
        flexDirection: 'row',
    },
    subdivisionTitle: {
        flex: 8,
    },
    lock: {
        width: 20,
        height: 20,
        flex: 1,
    },
    createNewDivision: {
        paddingTop: 10,
    },
    createNew: {
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderStyle: 'dashed',
        borderColor: '#A7ABB0',
        width: (width - 30) / 2,
        height: 230,
        flex: 1,
    },
    createnewpicwrapr: {
        flex: 1,
    },
    createnewpic: {
        alignItems: 'stretch',
        flex: 1,
    },
    createNewCircle: {
        width: 30,
        height: 30,
        borderRadius: 15,
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: '#A7ABB0',
        justifyContent: 'center',
    },
    createNewPlus: {
        fontWeight: 'bold',
        fontSize: 17,
        marginHorizontal: 5,
        color: '#A7ABB0',
    },
    newDiv: {
        paddingTop: 10,
    },
    myaccsec: {
        marginHorizontal: 10,
        marginBottom: 10,
        borderStyle: 'solid',
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderBottomWidth: 0,
        borderColor: '#E2E3E5',
    },
    styleaccwrapr: {
        padding: 10,
        borderStyle: 'solid',
        borderBottomWidth: 1,
        borderColor: '#E2E3E5',
    },
    styleacc: {
        color: '#696E79',
    },
    // manoj likes tab
    columnwrap: {
        flex: 1,
    },
    rowwrap: {
        flexDirection: 'row',
        flex: 1,
    },
    pricesLike:{
      flex:5,
    },
    priceNow: {
        fontWeight: 'bold',
        fontSize: 10,
        color: '#535864',
    },
    brandName: {
        fontSize: 11,
        color: '#686D78'
    },
    shownowStyle: {
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 10,
        color: 'white',
        fontWeight: 'bold',
    },
    
    rates: {
        flexDirection: 'row',
        flex:1,
    },
    textwrap: {
        padding:10,
    },
    productwholewrapr:{
      paddingRight:10,
      flex:1,
    },
    productwrap: {
        borderStyle: 'solid',
        borderWidth: 1,
        borderColor: '#E2E3E5',
        backgroundColor:'#ffffff',
        flex:1,
        alignItems:'center',
    },
    Displaypic: {
        height:200,
        width:(width-32)/2,
    },
    Displaypicimage: {
        flex: 1,
    },
    threedotspicwrapr:{
      flex: 1,
      alignItems:'flex-end',
      justifyContent:'flex-end',
      marginLeft:60,
    },
    threedotspic: {
        width: 30,
        height: 30,
    },
    threedots: {
        flex: 1,
    },

});
module.exports = ProfilePage;

**Comment by skv-headless** [comment]
Hello @rashmi-chachan could you please improve issue. png or gif with bug would be awesome. Attach small piece of code which doesn't work.

**Comment by skv-headless** [comment]
@rashmi-chachan please improve bug report and reopen issue.
