### ISSUE TITLE
Not maintaining history with RN 17.0 android

### ISSUE THREAD

**Issue by MuruganDurai** [brentvatne/react-native-scrollable-tab-view#114]
Hi, It seems like,rn-stb is not maintaining the previously selected tab when coming back instead it is going to default tab. Could you please check this is issue? Have used component with 13.1 which maintains history.

**Comment by 9mm** [comment]
Hmm I thought I was going crazy. So this component is supposed to maintain it's current page when props change and the component redraws right? I've never used this component before and I wasn't sure if this was expected behavior

**Comment by MuruganDurai** [comment]
I think @brentvatne can confirm that behaviour.

**Comment by josebalius** [comment]
+1 interested in the answer for this.

**Comment by josebalius** [comment]
I got this to work locally by simple checking for an initialPage to be set, otherwise rely on history, and it seems to work nicely for me. @brentvatne PR submitted if interested.

**Comment by MuruganDurai** [comment]
@josebalius setting the initialPage at onChangeTab solves the problem but loading the tabs very slow.

**Comment by josebalius** [comment]
@MuruganDurai ah :/ I don't use initialPage that's why the solution worked for me.

@skv-headless I guess the question is, why do we have to go back to the initialPage when props change? I am sure this requirement happened at some point.

**Comment by 9mm** [comment]
I'm also wondering if that's expected behavior or not, I can't tell from this thread. The problem is I'm showing this component for search results, and every time search results change it keeps going back to page 1. I was hoping the above pull request fixed it but I have the same issue. Am I missing something or is this expected behavior for this component? Is there a way not to have it do that?

**Comment by josebalius** [comment]
@9mm Thats exactly my use case (a lot like instagram's search page) but I don't use initialPage since I am fine with the first tab being the initialPage, and it works for me.

**Comment by 9mm** [comment]
When I delete initialPage it still does the same thing for me. Can I maybe see your code?

**Comment by josebalius** [comment]
@9mm I'll try to post something tonight but make sure you have the latest of this repo, specifically this PR: https://github.com/brentvatne/react-native-scrollable-tab-view/issues/118

If you don't its very easy to go into the node_modules/folder and change the one line (its just one line) and rebuild your RN project so you can test it.

**Comment by 9mm** [comment]
Ahhh that's probably it. I'll try that first. Thanks!

**Comment by 9mm** [comment]
Damn... no dice. Does all this look right to you?

      <View style={globalStyles.container}>
        <ScrollableTabView
          tabBarPosition="top"
          tabBarUnderlineColor={globalStyles.colors.brand}
          tabBarInactiveTextColor="#fff"
          tabBarActiveTextColor={globalStyles.colors.brand}>
            <View style={{flex: 1}} tabLabel="All">{paneAll}</View>
            <View style={{flex: 1}} tabLabel={formatTab('Artists', stats.artists)}>{paneArtists}</View>
            <View style={{flex: 1}} tabLabel={formatTab('Tracks', stats.tracks)}>{paneTracks}</View>
            <View style={{flex: 1}} tabLabel={formatTab('Albums', stats.albums)}>{paneAlbums}</View>
        </ScrollableTabView>
      </View>

**Comment by josebalius** [comment]
Looks fine to me, make sure you kill the Packager and rerun it from xcode just in case you have cached code.

**Comment by 9mm** [comment]
Do you mean `react-native run-android`? Or do I actually do something in Xcode for an Android project? 

I did kill the packager.

Sorry for the questions, kind of new to this and this is the one last remaining issue/bug that I just am struggling wtih

**Comment by 9mm** [comment]
Nevermind... the router is redrawing everything. Sorry

**Comment by MuruganDurai** [comment]
@josebalius everything works fine to me with that fix.
