### ISSUE TITLE
Fails when there is only one tab

### ISSUE THREAD

**Issue by grischoun** [brentvatne/react-native-scrollable-tab-view#117]
On the simple example, trying to show only one tab fails.

```javascript
var SimpleExample = React.createClass({
  render() {
    return (
      <ScrollableTabView style={{marginTop: 20}}>
        <Text tabLabel='Tab #1'>My</Text>
        // <Text tabLabel='Tab #2'>favorite</Text>
        // <Text tabLabel='Tab #3'>project</Text>
      </ScrollableTabView>
    )
  }
});
```javascript

It does not make sense to have only one tab but still you might want to have a look.

**Comment by skv-headless** [comment]
please try 
```rm -rf node_modules```
```npm i```

**Comment by skv-headless** [comment]
@grischoun I cant reproduce this bug. If it steel an issue for you and my tip doesn't help please reopen issue.

**Comment by grischoun** [comment]
@skv-headless Sorry for late reply. It is working now for me too. Thanks!

**Comment by punitlohani93** [comment]
I am not able to get this working on android. Works like a charm on iOS. The tabs won't swipe neither would the particular tab content be rendered. I removed all styles and data to check if I may have entered something wrong, yet the issue persists. Please have a look at it. No issues in iOS

Android: 
![screen shot 2016-04-05 at 5 57 57 pm](https://cloud.githubusercontent.com/assets/17720337/14281765/990d2efe-fb58-11e5-8f14-ac68189bbc02.png)

iOS:
![screen shot 2016-04-05 at 5 58 35 pm](https://cloud.githubusercontent.com/assets/17720337/14281774/a0b6499c-fb58-11e5-924e-0f40b78bde3a.png)

`render() {
		
		return(
				<View style={{marginTop: 56}}>
						<ScrollableTabView tabBarInactiveTextColor="#333" tabBarActiveTextColor="#333" tabBarUnderlineColor="#ED1C24">
							<View tabLabel="A">
							</View>
							<View tabLabel="B">
							</View>
							<View tabLabel="C">
							</View>
						</ScrollableTabView>
      				</View>
				
			
			)
	}`

Would love to know if I missed anything. Keep up the good work.
