### ISSUE TITLE
React Native 0.7.1 - "undefined is not an object (evaluating 'Dimensions.get')

### ISSUE THREAD

**Issue by irfaan** [brentvatne/react-native-scrollable-tab-view#12]
Receiving this error. Also:
```
<unknown>
DefaultTabBar.js:12
```

Digging around but I'm not quite sure what needs to change o_O

**Comment by brentvatne** [comment]
@ifraan - hey there, sorry about that, the newest version (0.1.8) only works on 0.8.0-rc and higher actually - try installing 0.1.7 instead :smile:

**Comment by brentvatne** [comment]
Updated package.json here to make it clear: https://github.com/brentvatne/react-native-scrollable-tab-view/commit/1e24cc279fb081ebd49fdcb0563da1ae63fe1154

**Comment by irfaan** [comment]
Now hitting this error:
```
Requiring unknown module "rebound". If you are sure the module is there, try restarting the packager.
```

**Comment by irfaan** [comment]
Thanks so much for such a wonderful plugin!

**Comment by brentvatne** [comment]
:)
