### ISSUE TITLE
Android Version

### ISSUE THREAD

**Issue by digitalhobo** [brentvatne/react-native-scrollable-tab-view#123]
Great module, thanks for sharing. Is the module supposed to work on android,
I seem to get a few errors and performance issues.
:0)

**Comment by skv-headless** [comment]
@digitalhobo hi. It supposed to work on android. Bug reports are welcome.

**Comment by fxhereng** [comment]
+1. I'm experiencing as well some performances issues, at launching it doesn't respond after 2 or 3 seconds. I'm using a tab bar with images, that's maybe why it is slow...

**Comment by skv-headless** [comment]
I think it is not related to scrollable tab view. React native cant render a lot of content fast. https://facebook.github.io/react-native/docs/performance.html it might be helpfull.

**Comment by fxhereng** [comment]
Well seen, I deactivated the the debug mode, and it's working like a charm :+1:

**Comment by skv-headless** [comment]
@digitalhobo please open new issue with explanation of your problem.

**Comment by digitalhobo** [comment]
Thanks skv-headless & fxhereng, got it working now. :+1:
