### ISSUE TITLE
change fontSize

### ISSUE THREAD

**Issue by L-Jovi** [brentvatne/react-native-scrollable-tab-view#127]
I want to change `ScrollView` property `tabLabel` display text size that trying to add style like `fontSize: [number]`, but it not work.

how could I change tabLabel text size?  thanks for your time..

**Comment by skv-headless** [comment]
You can create https://github.com/brentvatne/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookTabBar.js custom tab bar and use it like https://github.com/brentvatne/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookTabsExample.js#L18

**Comment by L-Jovi** [comment]
thanks, I'll try it.
