### ISSUE TITLE
Whenever I updateState, scrolls back to initial tab

### ISSUE THREAD

**Issue by yogiben** [brentvatne/react-native-scrollable-tab-view#128]
In my small app, whenever I update the state e.g.

```
this.setState({
      text: text
    })
```

The tab bar slides back to the original tab.

Running on iOS.

**Comment by ghamaide** [comment]
+1

**Comment by yogiben** [comment]
This is a simple example that replicates the error
```
var Tabs = React.createClass({
  getInitialState() {
    return {
      tab: 0
    }
  },
  handleTabChange(e) {
    this.setState({
      tab: e.i
    })
  },
  render() {
    return (
      <ScrollableTabView onChangeTab={this.handleTabChange}>
        <TestView />
        <TestView />
        <TestView />
      </ScrollableTabView>
    );
  }
})
```

**Comment by yogiben** [comment]
Debugging package:

Any change in state of the parent element will trigger `componentWillReceiveProps`

```
componentWillReceiveProps(props) {
    if (props.initialPage !== this.state.currentPage) {
      this.goToPage(props.initialPage);
    }
  },
```

This will get check the `initialPage` prop agains the `this.state.currentPage` and return to the current page if if doesn't match.

**Comment by yogiben** [comment]
Created PR #129

**Comment by skv-headless** [comment]
Please check master version.

**Comment by robtg4** [comment]
@skv-headless could you go into more detail with your reply? where in master version should we check? How can we solve this?

**Comment by skv-headless** [comment]
I use v0.3.5 #129 fixed for me.
