### ISSUE TITLE
Adjust speed at which animation occurs

### ISSUE THREAD

**Issue by irfaan** [brentvatne/react-native-scrollable-tab-view#13]
Hi! I've been playing around with spring tension and friction, but how do I adjust the overall speed at which the transition takes place?

Thanks again for all of your work on this plugin!

**Comment by brentvatne** [comment]
@irfaan - you can adjust that with a combination of tension and friction, those are the only factors that affect it. I was thinking about replacing the underlying transition to decay so it can factor in acceleration better, would that help?

**Comment by irfaan** [comment]
Hi @brentvatne - Yes. If I'm understanding you correctly, I think that matching acceleration would make the transition feel more natural. Provided, of course, if there is a minimum speed that we can set so account for extremely slow swipes. What do you think?

**Comment by brentvatne** [comment]
Yeah we would definitely have to set a minimum acceleration, like I did with swipes on https://github.com/brentvatne/react-native-animated-demo-tinder :) Do you want to have a try at replacing the animations in this with the `Animated` library?
