### ISSUE TITLE
Early Component Mount!

### ISSUE THREAD

**Issue by DHidee66** [brentvatne/react-native-scrollable-tab-view#131]
Hi,

When the ScrollBarView is mounted all of the tabs are mounted too. 
Is there a way to wait until the tab is open to mount it?

Thank You!

**Comment by skv-headless** [comment]
Sure. Easiest way for every tab put state like ```showPlaceholder: true``` and when tab selected set it to ```showPlaceholder: false```. There are better solutions.

**Comment by DHidee66** [comment]
@skv-headless The issue is here: The second tab that hasn't been opened calls a function in the ``componentDidMount`` and it changes state when ``componentWillReceiveProps``. 
And of course I get a warning saying I can't change the state of an unmounted component.
I finally found a workaround but it would be nice if the tab that hasn't been opened called the ``componentDidMount`` function when it is open.

**Comment by skv-headless** [comment]
I'm quite good with a fact that ```componentDidMount``` called immediately. We can think about ```lazy``` parameter that would work as you described.

**Comment by skv-headless** [comment]
I think we can close this issue. #70 is about lazy loading.
