### ISSUE TITLE
change view like dropdown list

### ISSUE THREAD

**Issue by L-Jovi** [brentvatne/react-native-scrollable-tab-view#132]
hi, thanks for your smart project and I'd really love it.

if I want to change tabbar display like dropdown as [here](https://github.com/alinz/react-native-dropdown#demo),  how could I do?

thanks.

**Comment by skv-headless** [comment]
I think it is possible to do with custom tabBar, there you can just remove tabs.

**Comment by L-Jovi** [comment]
thank you
