### ISSUE TITLE
How to disable the vertical scroll ?

### ISSUE THREAD

**Issue by JeremDsgn** [brentvatne/react-native-scrollable-tab-view#134]
Hi!

I would like to disable the vertical scroll. I found the horizontal props, on the source code, and it works well at `false` to disable the horizontal scroll. What's the equivalent for the vertical scroll ?

I am using the scrollable tab view on a card, above an image, and this card, is already in a scrollview. I believe this error https://github.com/facebook/react-native/issues/1501 is also came from this double use of scrollview.

Thanks

**Comment by JeremDsgn** [comment]
Help wanted @skv-headless :)

**Comment by skv-headless** [comment]
@JeremDsgn hi. ```react-native-scrollable-tab-view``` doesn't create vertical scroll. I'm not sure that I understand what do you mean. If you make screenshot It will help a lot.

**Comment by JeremDsgn** [comment]
Hi @skv-headless here is a little drawing of the issue.

![group 2](https://cloud.githubusercontent.com/assets/937328/12733277/347b225c-c93a-11e5-8f4b-dc5d4d754e49.jpg)

**Comment by skv-headless** [comment]
Why do you need scrollview if you don't need scroll? Probably code will clarify things to me

**Comment by JeremDsgn** [comment]
I already have a scrollview who wrap the `scrollable-tab-view` component. That's why I want to disable the vertical scroll in the `scrollable-tav-view` component.

```jsx
<ScrollView>
  <Image />
  <View style={{ height: 500 }}>Informations card</View>

  <ScrollableTabView renderTabBar={() => <CardTabBar />}>
    <Reviews
      tabLabel="Reviews"
      reviews={ reviews }
    />

    <Photos
      tabLabel="Photos"
      photos={ photos }
    />
  </ScrollableTabView>
</ScrollView>
```

**Comment by skv-headless** [comment]
@JeremDsgn but ```scrollable-tab-view``` doesn't create vertical scroll. Only horizontal and put all children there. Are you talking about ios or android?

**Comment by skv-headless** [comment]
BTW you can create a PR to an example to show your issue.

**Comment by JeremDsgn** [comment]
I don't get it.

![image](https://raw.githubusercontent.com/brentvatne/react-native-scrollable-tab-view/master/demo.gif)

Here on the example you have both vertical and horizontal scroll, right ?

Here you use a ScrollView https://github.com/brentvatne/react-native-scrollable-tab-view/blob/master/index.js#L83 who create both horizontal and vertical scroll right ?

So, the only thing I want to do, is disable the vertical scroll on the ScrollView and the content height would fit to the content itself.

Is there something I missed ? I hope you understand better.

**Comment by skv-headless** [comment]
It is old example on the png. https://github.com/brentvatne/react-native-scrollable-tab-view/blob/master/index.js#L84 there is ```horizontal``` option. What version ```react-native-scrollable-tab-view``` do you use?

**Comment by JeremDsgn** [comment]
OK, I didn't look at the right place. I display my items inside the `react-native-scrollable-tab-view` component with a `ListView` and this is this one who created the scroll effect. --' `scrollEnabled={ false }` works good !

Sorry for this and thanks !
