### ISSUE TITLE
Does this work with 0.18

### ISSUE THREAD

**Issue by miknonny** [brentvatne/react-native-scrollable-tab-view#145]
I have been trying to make this work with 0.18. it just seems to crash with Xcode. Has anyone got any ideas.?

**Comment by grabbou** [comment]
Works fine on 0.19

**Comment by skv-headless** [comment]
What error message do you get?

**Comment by miknonny** [comment]
Sorry. I think it was my mistake. I started a new Project and it works. I think i will now make same incremental changes i made earlier and see if i can recreate the error message.

**Comment by skv-headless** [comment]
@miknonny did you solve it?

**Comment by miknonny** [comment]
@skv-headless yes i did. Works perfectly now! thanks. I think Xcode crashed when i was trying to make  it a child of [react-native-side-menu-component](https://github.com/react-native-fellowship/react-native-side-menu).
