### ISSUE TITLE
Can we remove container height management?

### ISSUE THREAD

**Issue by mosesoak** [brentvatne/react-native-scrollable-tab-view#151]
I need to resize the component's height, but it jams that action due to the fact that it is trying to manage its height on its own:

    if (width !== container.width || height !== container.height) {
      this.setState({container: e.nativeEvent.layout});

If I comment out the second condition that checks height, everything works fine.

What I'm wondering is, does this component really need to manage its height manually? Perhaps it could just rely on its flex:1 container and then actively manage and monitor its width, since it is primarily a horizontal scroll view.

**Comment by mosesoak** [comment]
I've written a PR for this but figure we can discuss it here first before I submit it, don't want to overload you guys with requests! Thanks for your hard work.

**Comment by skv-headless** [comment]
I don't mind your solution. It really doesn't use ```height```. Just curious what problem do you have with keeping height in state?

**Comment by mosesoak** [comment]
Cool. I have a conflict in my project with this, where I'm purposefully resizing the component's height and it keeps detecting this and re-laying itself out which jams up my animation. If it's not needed it might be cleaner to remove it. Thanks!
