### ISSUE TITLE
How might I attach an onPress to goToPage(x)?

### ISSUE THREAD

**Issue by irfaan** [brentvatne/react-native-scrollable-tab-view#16]
I am trying to use a <TouchableOpacity> onPress from within a tab to switch tabs. Do you happen to know how I might access goToPage() in ScrollableTabView from within a tab? Is that the right function?

Thank you in advance!

**Comment by irfaan** [comment]
Used a reference on ScrollableTabView to access ```goToPage()```.

```
<ScrollableTabView
	ref="ScrollableTabs" 
	...
/>

[...]

<TouchableOpacity 
	onPress={
		event => this.refs.ScrollableTabs.goToPage(0)
	} 
```

**Comment by brentvatne** [comment]
Great :) Sorry for not getting back to you
