### ISSUE TITLE
Invalid prop `scrollOffset`

### ISSUE THREAD

**Issue by L-Jovi** [brentvatne/react-native-scrollable-tab-view#164]
when I update to new version `0.3.6` and apply `ScrollableTabBar` in my existed project, tab bar can't appear until sliding screen, then some warning output below.

    Failed propType: Invalid prop `scrollOffset` of type `string` supplied to `ScrollableTabBar`, expected `number`. Check the render method of `ScrollableTabView`

any ideas?
thanks for your time.

**Comment by skv-headless** [comment]
https://github.com/brentvatne/react-native-scrollable-tab-view/blame/master/ScrollableTabBar.js#L18 I think here should be number. Could you try?

**Comment by L-Jovi** [comment]
yes, number type is right, thank you : )

**Comment by skv-headless** [comment]
Will you make a PR?

**Comment by L-Jovi** [comment]
with my pleasure : )
