### ISSUE TITLE
Tab bar animation lags during fling gestures

### ISSUE THREAD

**Issue by danhawkes** [brentvatne/react-native-scrollable-tab-view#166]
I'm seeing the tab bar animation lag behind the scroll position during fling actions.

[Demo video](https://sendvid.com/bydncmy4)

_(For the first bit of this, I'm swiping between pages and you see the issue. Later on, I'm manually scrolling at a similar speed and the tab bar is smoothly scrolled.)_

Any ideas why this is? I suspect it may be related to the values coming out of the `scrollValue` prop passed to the tab bar, which seem to be jumping in large chunks:

    0.07866666666666666
    0.07866666666666666
    0.07866666666666666
    0.07866666666666666
    0.196
    0.196
    0.196
    0.196
    0.196
    0.22933333333333333
    0.22933333333333333
    0.22933333333333333
    0.22933333333333333
    0.22933333333333333
    0.22933333333333333
    0.4106666666666667
    0.4106666666666667
    0.4106666666666667
    0.4106666666666667
    0.4106666666666667
    0.4106666666666667
    0.508
    0.508
    0.508
    0.508
    0.508
    0.508
    0.6693333333333333
    0.6693333333333333
    0.6693333333333333
    0.6693333333333333
    0.6693333333333333
    0.6693333333333333
    0.74
    0.74
    0.74
    0.74
    0.74
    0.74
    0.8386666666666667
    0.8386666666666667
    0.8386666666666667
    0.8386666666666667
    0.8386666666666667
    0.8386666666666667
    0.8773333333333333
    0.8773333333333333
    0.8773333333333333
    0.8773333333333333
    0.8773333333333333
    0.8773333333333333
    0.908
    0.908
    0.908
    0.908
    0.908
    0.908
    0.9346666666666666
    0.9346666666666666
    0.9346666666666666
    0.9346666666666666
    0.9346666666666666
    0.9346666666666666
    0.968
    0.968
    0.968
    0.968
    0.968
    0.968
    0.9853333333333333
    0.9853333333333333
    0.9853333333333333
    0.9853333333333333
    0.9853333333333333
    0.9853333333333333
    0.9946666666666667
    0.9946666666666667
    0.9946666666666667
    0.9946666666666667
    0.9946666666666667
    0.9946666666666667
    1
    1
    1
    1
    1
    1

**Comment by skv-headless** [comment]
First of all try to make production javascript build. It usually match better that development.

**Comment by skv-headless** [comment]
Feel free to reopen issue if it doesn't help.
