### ISSUE TITLE
Something wrong when have TabBarIOS in code

### ISSUE THREAD

**Issue by h3l** [brentvatne/react-native-scrollable-tab-view#168]
I want use react-native-scrollable-tab-view in my project.
but there is some problem.
When I use it single, everything is OK like below:
![normal](https://cloud.githubusercontent.com/assets/1664952/13195591/418d62a0-d7f1-11e5-9df4-3390d16e2dcb.gif)

But when I use it with TabBarIOS,there have some problem like below:
![abnormal](https://cloud.githubusercontent.com/assets/1664952/13195604/b2ce6fa4-d7f1-11e5-9274-4234aff93d6f.gif)

**Comment by h3l** [comment]
here is the demo code
https://github.com/h3l/try_sample

**Comment by skv-headless** [comment]
@h3l do you mean content margin from tab bar which stays after scroll?

**Comment by h3l** [comment]
@skv-headless thanks very muck, with your help, i find just add automaticallyAdjustContentInsets={false}  to ScrollView fix it.
