### ISSUE TITLE
Focus issue when TextInput is inside ScrollableTabView

### ISSUE THREAD

**Issue by danhawkes** [brentvatne/react-native-scrollable-tab-view#175]
Normally, when you have multiple TextInputs, you can switch focus between them with a single tap. The tapped field receives focus, and the keyboard remains visible.

When embedded in ScrollableTabView, this changes - the first tap blurs the focused TextInput and dismisses the keyboard, and then another tap is required to focus the field.

Demo with the FacebookTabsExample [here](https://github.com/danhawkes/react-native-scrollable-tab-view/tree/focus-issue).

**Comment by K-Leon** [comment]
I experienced this myself. This is related to RN Issue #4087 (https://github.com/facebook/react-native/issues/4087 )

To fix this you need to add this to the tabview: 

##
        keyboardDismissMode='on-drag'
        keyboardShouldPersistTaps={true}
## ( would be great to merge this upstream.. but i'm not sure if this has unwanted sideeffects for other usecases. )

And a custom Eventlistener:
##
onStartShouldSetResponderCapture={(e) => {
  const target = e.nativeEvent.target;
  if (target !== React.findNodeHandle(this.refs.email) && target !== React.findNodeHandle(this.refs.password)) {
    this.refs.email.blur();
    this.refs.password.blur();
  }
}}
##

**Comment by skv-headless** [comment]
@danhawkes https://github.com/danhawkes/react-native-scrollable-tab-view/commit/775d3f4d41c40458558125923b2d1182ded25010 if you replace ```this.props``` with ```this.props.contentProps``` it would be great feature.

**Comment by skv-headless** [comment]
@danhawkes can I close it?

**Comment by danhawkes** [comment]
Ah yep, thanks, will do.
