### ISSUE TITLE
Add pull to refresh functionality for both android and iOS

### ISSUE THREAD

**Issue by ghuh** [brentvatne/react-native-scrollable-tab-view#179]

**Comment by nvcken** [comment]
Hi, How to find out this ?

**Comment by nvcken** [comment]
I tried component as this [https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/RefreshControlExample.js](url) to `ScrollableTabView`
But refresh control does not show
```js
<ScrollableTabView initialPage={0} renderTabBar={() => <EvasionTabBar />}>
        <ScrollView tabLabel="Current" style={styles.tabView}>
          <View style={styles.card}>
            <RefreshControlExample/>
          </View>
        </ScrollView>
  </ScrollableTabView>
```

**Comment by ghuh** [comment]
The solution to this problem is to use a ScrollView or ListView within the ScrollableTabView that supports the refresh control:

`
var refreshControl = <RefreshControl refreshing = { this.state.refreshing } onRefresh = { this._onRefresh } />;

...

<ScrollableTabView>
    <ScrollView tabLabel = { "Label" } refreshControl = { refreshControl }>
        ...
    </ScrollView>
</ScrollableTabView>`

**Comment by JeffersonFilho** [comment]
There is any other way of having RefreshControl on other tabs without doing this way? It works fine on Android and doesn't on iOS?

**Comment by shiqian123** [comment]
I can when I used   pointerEvents="box-none"
<View  pointerEvents="box-none">
  <ListView  refreshControl = { refreshControl }></ListView>
</View>

**Comment by teodors** [comment]
@ghuh Do you mean having a ViewPagerAndroid backed ScrollableTabView or simply having direct childs ScrollView without View in between? Is there a way of having ScrollView within a ScrollView with RefreshControl not jamming?

**Comment by ghuh** [comment]
I'm not sure i follow the question.  If you look at my example above, putting a ScrollView as the top level within the ScrollableTabView and then adding the refresh control to the ScrollView results in scrolling and refreshing working on both iOS and Android.

**Comment by ghuh** [comment]
That's a different issue than this issue was originally created for.  Unfortunately, I don't have any insights that can help you with that.

**Comment by prasanth95** [comment]
> The solution to this problem is to use a ScrollView or ListView within the ScrollableTabView that supports the refresh control:
> 
> ```
> var refreshControl = <RefreshControl refreshing = { this.state.refreshing } onRefresh = { this._onRefresh } />;
> 
> ...
> 
> <ScrollableTabView>
>     <ScrollView tabLabel = { "Label" } refreshControl = { refreshControl }>
>         ...
>     </ScrollView>
> </ScrollableTabView>
> ```

In Android, it's showing blank screen
