### ISSUE TITLE
demo not working due to npm install issues

### ISSUE THREAD

**Issue by qbig** [brentvatne/react-native-scrollable-tab-view#18]
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "react-native@0.8.0-rc"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-native does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-icons@0.0.9 wants react-native@^0.5.0
npm ERR! peerinvalid Peer react-native-scrollable-tab-view@0.1.10 wants react-native@>=0.8.0 || 0.8.0-rc

**Comment by brentvatne** [comment]
Hey! This should work fine now, updated package.json
