### ISSUE TITLE
How to scroll tabbar horizontally?

### ISSUE THREAD

**Issue by rkostrab** [brentvatne/react-native-scrollable-tab-view#180]
I have more tabs with longer titles (they overlay each other) in my app. How to allow scrolling tabs in tabbar?

**Comment by skv-headless** [comment]
https://github.com/brentvatne/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookTabsExample.js#L70

**Comment by rkostrab** [comment]
Thanks for pretty quick answer! Btw, throwing this warning:
`W/ReactNativeJS( 2729): `scrollWithoutAnimationTo` is deprecated. Use `scrollTo` instead`
is causing wince of underline animation. I had to rewrite code in `node_modules` to run it smoothly. Please fix this in next update.

[In this file](https://github.com/brentvatne/react-native-scrollable-tab-view/blob/master/ScrollableTabBar.js)
Bad:
```
...
if (Platform === 'android') {
      this._scrollView.scrollWithoutAnimationTo(0, newScrollX);
    } else {
      const rightBoundScroll = this._tabContainerMeasurements.width - (this._containerMeasurements.width);
      newScrollX = newScrollX > rightBoundScroll ? rightBoundScroll : newScrollX;
      this._scrollView.scrollWithoutAnimationTo(0, newScrollX);
    }
...
```
Good:
```
...
if (Platform === 'android') {
      this._scrollView.scrollTo(0, newScrollX);
    } else {
      const rightBoundScroll = this._tabContainerMeasurements.width - (this._containerMeasurements.width);
      newScrollX = newScrollX > rightBoundScroll ? rightBoundScroll : newScrollX;
      this._scrollView.scrollTo(0, newScrollX);
    }
...
```

Or if you want, I can open the pull request.

**Comment by skv-headless** [comment]
It would be great

**Comment by rkostrab** [comment]
Okay, so [here](https://github.com/brentvatne/react-native-scrollable-tab-view/pull/181) we go :)
