### ISSUE TITLE
Can't lock horizontal dragging.

### ISSUE THREAD

**Issue by tugucci** [brentvatne/react-native-scrollable-tab-view#188]
`<ScrollableTabView  initialPage={0} locked = 'true' renderTabBar={() => <FacebookTabBar/>}>`

This doesn't work, am I doing something wrong?
Thanks in advance!

**Comment by skv-headless** [comment]
```locked={true}```

**Comment by tugucci** [comment]
Hi, sorry, I cannot see your answer for some reason. @skv-headless

**Comment by brentvatne** [comment]
@tugucci - i just edited it, should be visible now :)

**Comment by tugucci** [comment]
Hm, it doesn't work on my example :/ , could it be something else? I have 
`<ScrollableTabView  initialPage={0} locked={true} renderTabBar={() => <FacebookTabBar/>}>
`
now.

**Comment by skv-headless** [comment]
doesn't work for android https://github.com/brentvatne/react-native-scrollable-tab-view/issues/95

**Comment by skv-headless** [comment]
@tugucci

**Comment by shidhincr** [comment]
+1
