### ISSUE TITLE
How to write in ES6?

### ISSUE THREAD

**Issue by zsf513** [brentvatne/react-native-scrollable-tab-view#192]
Why not write the example in ES6?Can you tell me how to write the FacebookTabBar.js in ES6?Thank you very much!

**Comment by Sunakujira1** [comment]
The example uses some functionality of ES6 such as arrow function, thus it is already in ES6.

**Comment by skv-headless** [comment]
In project there is eslint file. I'll accept all PR fixing eslint exception and migration to es6-es7 features (except classes for now)
