### ISSUE TITLE
Add tabIcon Property

### ISSUE THREAD

**Issue by cancan101** [brentvatne/react-native-scrollable-tab-view#195]
Add a `tabIcon` prop similar to `tabLabel` to make it easier to use Icons for each tab than having to use a custom `renderTabBar`.

**Comment by skv-headless** [comment]
I don't want to add dependency from https://github.com/oblador/react-native-vector-icons. And it is not flexible. For example if I want images instead tabs. I think it would be great to make something like ```renderTab``` property

**Comment by cancan101** [comment]
You are saying instead of adding `tabIcon`, add a  `renderTab` ?

**Comment by skv-headless** [comment]
Yep

**Comment by cancan101** [comment]
That was more or less what I had in mind. Perhaps the difference is that I was thinking `tabIcon` would take a component whereas I am thinking `renderTab` takes a function that returns a component?

**Comment by skv-headless** [comment]
I think the same way about ```renderTab```

**Comment by skv-headless** [comment]
I'll be waiting for PR :wink:

**Comment by cancan101** [comment]
Should `renderTab` be settable for each tab? or should there be one prop that is used for entire tabbar (ie allow overriding [this](https://github.com/brentvatne/react-native-scrollable-tab-view/blob/321194523af7f7db467ee487fb0c1455d17137d2/DefaultTabBar.js#L44-L56))?

**Comment by skv-headless** [comment]
I think one. Because usually tabs are similar. One note. Could you please make that property for tabBars. Not for main component. I want to separate this entities

**Comment by mschipperheyn** [comment]
I would go with https://github.com/brentvatne/react-native-scrollable-tab-view/issues/240 instead. That way you can add any kind of design, icons, text whatever

**Comment by skv-headless** [comment]
close for #240
