### ISSUE TITLE
FacebookTabBar Opacity Calculation

### ISSUE THREAD

**Issue by jhprks** [brentvatne/react-native-scrollable-tab-view#2]
In FacebookTabBar.js, it looks like setAnimationValue is not calculating the icon opacity correctly.

Initial app launch.

![screen shot 2015-06-21 at 4 09 58 pm](https://cloud.githubusercontent.com/assets/1529857/8273784/62362ae0-1830-11e5-8a2a-059500068bb5.png)

After selecting the 5th icon.

![screen shot 2015-06-21 at 4 09 42 pm](https://cloud.githubusercontent.com/assets/1529857/8273786/73f4d90c-1830-11e5-98e9-bbf4304c5b61.png)

**Comment by brentvatne** [comment]
Hi there, this doesn't happen for me, can you post your code?

![nope](https://cloud.githubusercontent.com/assets/90494/8275984/b01cb376-1864-11e5-97b3-956c1d4f3192.gif)

**Comment by jhprks** [comment]
After hours of searching for "the code" that produced this behavior, I noticed it was just an issue related to the simulator. I stopped seeing that issue immediately after resetting iOS simulator's content and settings.

**Comment by brentvatne** [comment]
@jhprks - super weird, thanks for letting me know

**Comment by jhprks** [comment]
@brentvatne Yeah no problem, I'll post if I run into any issues. Thanks.
