### ISSUE TITLE
Is there a way to change the tab view through programming ?

### ISSUE THREAD

**Issue by piyushchauhan2011** [brentvatne/react-native-scrollable-tab-view#20]
Is there any way by which we can change the current tab we are viewing to the index one we want through code without clicking ?
like:
`setTabView` function or so ?

**Comment by psbanka** [comment]
This would definitely be a nice feature :+1:

**Comment by piyushchauhan2011** [comment]
:+1:

**Comment by achang28** [comment]
I've come up with a quick fix solution. Will post soon. Probably not elegant but at least it's working.  It involves passing the "goToPage" function (from the custom tab bar) to the parent component, and then assigning goToPage to a variable on the parent component's state. This variable would then be pased in as props to each of the child component pages

**Comment by achang28** [comment]
Example:  https://github.com/achang28/TabView-RN

**Comment by irfaan** [comment]
Give ScrollableTabView a `ref` prop (e.g. `ref="Tabs"`) and then use its reference to use ScrollableTabView's `goToPage()` (e.g. `this.refs.Tabs.goToPage(1);`)

**Comment by brentvatne** [comment]
what @irfaan said ;)

**Comment by dannyprice1990** [comment]
I still can't get this to work unfortunately, can you provide a full example?

Thanks

**Comment by irfaan** [comment]
@dannyprice1990 Can you share the pertinent pieces of your application in a gist or put something up on http://rnplay.org?

**Comment by dannyprice1990** [comment]
Hey bud, I'm trying to change the tab using a button within the Ready2WorkComponent. Am I going about this in the wrong way?

![capture](https://cloud.githubusercontent.com/assets/12933723/10445095/e94f75e4-71b9-11e5-8a1c-5f8b4082d341.PNG)

From within component: 
![capture](https://cloud.githubusercontent.com/assets/12933723/10445133/5b15257a-71ba-11e5-9d9d-02aa3cc812c6.PNG)

Thanks for your help

**Comment by irfaan** [comment]
```this``` is likely referencing your ```Ready2WorkComponent```. Not sure how to make reference to something outside of it. 

@brentvatne, this is beyond the scope of your package, but do you know how to achieve this?

**Comment by JonathanWi** [comment]
Just stumbled on your issue and found a solution (a bit messy, but it works):

#### In the parent component (ScrollableTabView)

Like you did, add `ref="Tabs"` on the `ScrollableTabView` and add a `tabsRef` on each slides

````
<ScrollableTabView activeTab={1} ref="Tabs">
      <Profile tabsRef={this.state.tabsRef} tabLabel="a" />
      <Feed tabsRef={this.state.tabsRef} tabLabel="b" />
      <Settings tabsRef={this.state.tabsRef} tabLabel="c" />
</ScrollableTabView>
````

We could try to pass `{this.refs.Tabs}` instead of `{this.state.tabsRef}`; Unfortunately, it appears that `ref` is set **after** `componentDidMount` is called. What we need to do is declare:

````
getInitialState: function(){
  return {
    tabsRef : {} // At this point we don't have access to the ref
  }
},
componentDidMount: function(){
  this.setState({tabsRef : this.refs.Tabs}); // The this.refs.Tabs is now defined, and passed to the components
}
````

#### In the child component

We have now access to `this.props.tabsRef` and thus can call `this.props.tabsRef.goToPage(1)`

Hope this helps, it works for me!

**Comment by BalalRaza** [comment]
@irfaan @brentvatne Alongside goToPage(), can we also pass some props to the target page?
