### ISSUE TITLE
when you click a tab, in between tabs sometimes get colored

### ISSUE THREAD

**Issue by faceyspacey** [brentvatne/react-native-scrollable-tab-view#201]
when you swipe it works fine, but when you click a far away tab (i.e. the 5th tab, when you're on the first), it will leave a trail of color behind on the tabs in between. Like, they will be highlighted, but at varying opacities.

**Comment by skv-headless** [comment]
Do you mean facebook tab bar?

**Comment by faceyspacey** [comment]
yea.

**Comment by skv-headless** [comment]
fixed here https://github.com/brentvatne/react-native-scrollable-tab-view/commit/8b14d58bcf4c0588ddf6cf8024513540839d17eb . Thanks for report :+1:
