### ISSUE TITLE
Nesting Scrollable-Tab-View within another Scrollable-Tab-View DOESNOT WORK PORPERLY

### ISSUE THREAD

**Issue by liaq192** [brentvatne/react-native-scrollable-tab-view#209]
Hi , 
  I was working with nesting one scrollable-tab-view within another. The problem is that inner scrollable-tab-view doesnot work properly. It doesnot show tab data in inner Scrollable-Tab-View. As well as the manipulation in inner-scrollable-view-tabs doesnot work properly also.
I am attaching the example index.android.js file 

STV Version : react-native-scrollable-tab-view@0.4.0 
React-Native-Version :
--- react-native-cli: 0.1.10
--- react-native: 0.21.0

[index.android.txt](https://github.com/brentvatne/react-native-scrollable-tab-view/files/181989/index.android.txt)

**Comment by brentvatne** [comment]
Hi there! You're welcome to try to fix this issue but this was never a use case that I had in mind and I'm not sure it's something that @skv-headless is interested in working on either

**Comment by skv-headless** [comment]
#107
