### ISSUE TITLE
too many render cause navigator transitions slowly

### ISSUE THREAD

**Issue by L-Jovi** [brentvatne/react-native-scrollable-tab-view#210]
I have to put many components because of complex logic, and I find that slowly transitions when  execute navigator `push()`.

![performance](https://cloud.githubusercontent.com/assets/7262199/13915674/050c66b6-ef91-11e5-8ca7-f57d3ef18aa8.png)

what should I do now :(

thanks for your time.

regards.

**Comment by skv-headless** [comment]
Sorry I can't say anything without seeng a code and looking to interface.
When you run I code with ```dev=false``` it would be much better. Create new issue if you explain that it is related to ```react-native-scrollable-tab-view```
