### ISSUE TITLE
keyboardDismissMode="on-drag" breaks view

### ISSUE THREAD

**Issue by 9mm** [brentvatne/react-native-scrollable-tab-view#214]
Can we make this a prop you pass instead? Setting `keyboardDismissMode="on-drag"` breaks my app in some places.

**Comment by grabbou** [comment]
To put a little more background here - this only applies to Android. I am pretty sure this might be related to React Native itself, however worth discussing whether to make it as a prop or not.

Here's a simple view:
```
<View> <Input /> <TabView /> </View>
```

As user types letters - we fire requests to the API to fetch suggestions (think search view). As soon as first batch of results arrives (after first keystroke) - we render TabView initially and that blurs the keyboard!

**Comment by 9mm** [comment]
It appears you can actually pass contentProps to override defaults
