### ISSUE TITLE
Scrollable View

### ISSUE THREAD

**Issue by poom3d** [brentvatne/react-native-scrollable-tab-view#218]
I don't know where to put it. But I create a new repo and strip the tab component in case someone wants to use it without tab.

https://github.com/poom3d/react-native-scrollable-view

**Comment by skv-headless** [comment]
Have you tried ```<ScrollableTabView renderTabBar={() => null}/>```. I suppose result should be the same

**Comment by poom3d** [comment]
Oh, right. I did not know that I can send null to renderTabBar. But a cyclic scrollable view would be nice ;)
( Like scroll to the end and start to index 0)

**Comment by skv-headless** [comment]
Absolutely agree about cyclic swiping. Feel free to create an issue.
