### ISSUE TITLE
Disable the scroll position ?

### ISSUE THREAD

**Issue by shidhincr** [brentvatne/react-native-scrollable-tab-view#219]
Is there anyway to reset the scroll position to top when switching between the tabs ?

**Comment by skv-headless** [comment]
Sure. 
1) You need to create refs to your scroll components.
2) Then use ```onChangeTab``` callback here https://github.com/brentvatne/react-native-scrollable-tab-view#props
3) then call ```scrollTo``` method like here https://github.com/brentvatne/react-native-scrollable-tab-view/blob/master/index.js#L64
3)

**Comment by shidhincr** [comment]
@skv-headless Thanks

Sorry, but I forgot to mention that I wanted to get this working on Android. In Android, there is a `ViewPagerAndroid` component.

In my code, I have a scrollView inside this ViewPager component. I tried to call the `scrollTo` of the scrollView component, but it seems like not working.

**Comment by shidhincr** [comment]
@skv-headless Thanks for your help.

I could able to do it finally. I had an issue in my code that there were multiple scrollViews. I was trying to refer the wrong one that's why it didn't work earlier for me.

**Comment by coolsnow77** [comment]
@shidhincr  how to scrollTo . top?  my code is:  this.refs.tabView.scrollView.scrollTo({x: 2 * utils.dimensions.width, y: 50, animated: false})..  y value how to define? help? thanks...

**Comment by coolsnow77** [comment]
this.refs.tabView.scrollView.scrollTo({x: 2 * utils.dimensions.width, y: 0, animated: false}),
if u tab is listView, u have to scroll to top in the listView not the scrollTabView, ListView scroll to top,
this.ref.<ListViewName>.getScrollResponder().scrollTo({x: 0, y: 0, animated: false})
