### ISSUE TITLE
FacebookTabBar example errors

### ISSUE THREAD

**Issue by adarshmuthappa** [brentvatne/react-native-scrollable-tab-view#22]
Hey first of all great repo! 

I am facing an issue integrating the FacebookTabBar example. I get the error "icon.setNativeProps is not a function " in the function

setAnimationValue(value) {
    var currentPage = this.props.activeTab;

    this.unselectedTabIcons.forEach((icon, i) => {
      if (value - i >= 0 && value - i <= 1) {
        icon.setNativeProps({opacity: value - i});
      }
      if (i - value >= 0 &&  i - value <= 1) {
        icon.setNativeProps({opacity: i - value});
      }
    });
  },

Also, if I do a console.log(icon), it says icon is not defined
I had no problem integrating the CustomTabBar code. Thanks again!

**Comment by brentvatne** [comment]
hi there, not really sure what's going on with this one, maybe something has changed with a dependency, if you have a chance to investigate and fix a PR would be much appreciated!

**Comment by fomahaut** [comment]
Same issue with that, fixed with #40.
