### ISSUE TITLE
Android TabBar freezes

### ISSUE THREAD

**Issue by gaykov** [brentvatne/react-native-scrollable-tab-view#222]
The following code works as expected on iOS and freezes an android app. Inside the FPS-monitor I see -2.1 fps for JS thread after I'm trying to switch tab. Here's the code:

```javascript
render() {
    return (
        <ScrollableTabView>
            <Main tabLabel="fireball" />
            <Settings tabLabel="ios-gear-outline" />
        </ScrollableTabView>
    );
}
```

I'm using 0.4.0 version

**Comment by skv-headless** [comment]
1) try dev=false
2) try to make ```Main``` and ```Settings``` components smaller.

I think problem not with ```react-native-scrollable-tab-view```. Reopen if you find out that I'm wrong.
