### ISSUE TITLE
Yellowbox Warning for Deprecation of scrollTo() Method

### ISSUE THREAD

**Issue by nHiRanZ** [brentvatne/react-native-scrollable-tab-view#225]
Following Yellowbox warning is given with React Native 0.22.2

`scrollTo(y, x, animated) is deprecated. Use scrollTo({x: 5, y: 5, animated: true}) instead.`

**Comment by skv-headless** [comment]
you use 0.3.x version of ```react-native-scrollable-tab-view``` try to update.
