### ISSUE TITLE
How to put tab indicator at top of tabbar?

### ISSUE THREAD

**Issue by paynestrike** [brentvatne/react-native-scrollable-tab-view#227]
when set tabBarPosition = 'bottom' , the tab indicator also appear at bottom of tabbar, is there a option to put the indicator at top of tabbar?
![screenshot_2016-04-05-12-18-13](https://cloud.githubusercontent.com/assets/3880508/14271198/0366346a-fb29-11e5-96af-940af578b462.png)

**Comment by skv-headless** [comment]
I can make custom tab bar.
https://github.com/brentvatne/react-native-scrollable-tab-view/blob/master/DefaultTabBar.js
copy this file and swap lines 59 and 60.
