### ISSUE TITLE
Limit of tabs 

### ISSUE THREAD

**Issue by ramden** [brentvatne/react-native-scrollable-tab-view#229]
Tabs are currently limited to a fixed amount. I added 8 tabs and now it becomes unusable. Will there be a support for infinite number of pages/tabs? LIke on native android, the tabs above are scrollable horizontally

**Comment by skv-headless** [comment]
https://github.com/brentvatne/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookTabsExample.js#L59

**Comment by ramden** [comment]
Thanks ;)

**Comment by ozsirma** [comment]
The link is not working. 

I have a same problem. I have a lot of tabs. How I can do ?

**Comment by LyCharlie** [comment]
+1
I have a lot of tabs and I don't want to load off of them , is there any prop like setOffscreenPageLimit in android
