### ISSUE TITLE
All tabs get highlighted 

### ISSUE THREAD

**Issue by CoericK** [brentvatne/react-native-scrollable-tab-view#234]
See this video first: https://www.dropbox.com/s/hp4z7o59p0w6uur/Tabs%20Test.mov?dl=0
As you can see every time we change from the first tab to another tab every tab gets highlighted

Any clue why this happens?

**Comment by skv-headless** [comment]
https://github.com/brentvatne/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookTabBar.js#L30 it would be great if you find the reason.

**Comment by nihgwu** [comment]
I'll make a PR to solve this today, https://github.com/brentvatne/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookTabBar.js#L57 here is the wrong code

**Comment by nihgwu** [comment]
![hightlight](https://cloud.githubusercontent.com/assets/2595058/14585449/bb2e618e-04a8-11e6-82b4-430f06cf6256.gif)
