### ISSUE TITLE
onChangeTab called twice

### ISSUE THREAD

**Issue by uyson** [brentvatne/react-native-scrollable-tab-view#237]
why onChangeTab function called on tab change.?  is this a bug?

**Comment by skv-headless** [comment]
When it should be called?

**Comment by uyson** [comment]
@skv-headless  onChangeTab called twice

**Comment by jsphkhan** [comment]
Even I am getting this issue. Requesting the developer to look into this.

**Comment by brentvatne** [comment]
@uyson @jsphkhan - can you explain this in more detail, with some code to reproduce exactly what you're seeing and then also describe what you expect to see? thanks!

**Comment by nihgwu** [comment]
https://github.com/brentvatne/react-native-scrollable-tab-view/blob/master/index.js#L101-L108
the onChangeTab will be called twice because we have two trigger in one drag motion, i don't know why there should be a `onMomentumScrollBegin` handler, and the handler is buggy, i'll make a PR to fix it

**Comment by nihgwu** [comment]
![tabs](https://cloud.githubusercontent.com/assets/2595058/14585368/46c7a91c-04a4-11e6-9d6a-05e125a72269.gif)
the `_updateSelectedPage` is called both in `onMomentumScrollBegin` and `onMomentumScrollEnd`, and the page was calculated wrong, u can see that with a slight drag  the currentPage flash to n-1 in `onMomentumScrollBegin` then to n in `onMomentumScrollEnd` and that's the wrong behavior because the wrong calculation, the currentPage shouldn't be changed, and here is my solution:
``` js
          onMomentumScrollBegin={(e) => {
            const offsetX = e.nativeEvent.contentOffset.x;
            const page = Math.round(offsetX / this.state.containerWidth);
            if(this.state.currentPage != page){
              this._updateSelectedPage(page);
            }
          }}
          onMomentumScrollEnd={(e) => {
            const offsetX = e.nativeEvent.contentOffset.x;
            const page = Math.round(offsetX / this.state.containerWidth);
            if(this.state.currentPage != page){
              this._updateSelectedPage(page);
            }
          }}
```

**Comment by SudoPlz** [comment]
This created another problem. Now When onMomentumScrollEnd runs, and the `this.state.currentPage` is not updated yet, that will result on 
```js
  onMomentumScrollEnd={(e) => {
            const offsetX = e.nativeEvent.contentOffset.x;
            const page = Math.round(offsetX / this.state.containerWidth);
            if(this.state.currentPage != page){
              this._updateSelectedPage(page); //<-- This part
            }
          }}
```
this part of the code running and thus resulting on a second onChangeTab called, with the wrong page provided...! Now that a bug!
