### ISSUE TITLE
Tab bar text style is not applying my custom style

### ISSUE THREAD

**Issue by devbriguy** [brentvatne/react-native-scrollable-tab-view#238]
I followed the example and now I am trying to customize the tab bar's text style but after adding and reloading my app the style does not take affect. Here is my code: 

`      <ScrollableTabView tabBarTextStyle={{fontFamily: 'AvenirNext-Medium', fontSize: 20}}>
        <Text tabLabel='Events'>Events</Text>
        <Text tabLabel='Team'>Team</Text>
        <Text tabLabel='Shared Files'>Files</Text>
      </ScrollableTabView>
`

**Comment by skv-headless** [comment]
this props only in master. Today I'll publish new version to npm

**Comment by jvaclavik** [comment]
I tried to use 0.7.4, 0.6.7 (btw why 0.6.7 has newer release than 0.7.4?) and it still doesn't work. I can't figure out why. I found your implementation in DefaultTabBar.js:50 so it should be there.
