### ISSUE TITLE
react-native-vector-icons:processReleaseResources   FAILED

### ISSUE THREAD

**Issue by kjakah08** [brentvatne/react-native-scrollable-tab-view#239]
After install, I attempt to run, but the error appears:

:react-native-vector-icons:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-vector-icons:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.E
xecException: Process 'command 'C:\Users\KJA\AppData\Local\Android\sdk\build-too
ls\23.0.1\aapt.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 23.638 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by skv-headless** [comment]
try ```rm -rf node_modules``` then ```npm i```
