### ISSUE TITLE
how to stop video when swiping to another tab?

### ISSUE THREAD

**Issue by beebase** [brentvatne/react-native-scrollable-tab-view#245]
I'm looking for an event trigger that I can use in order to pause a react-native-video when I leave the screen. One of the tabs contains a video component.

I tried using the onTabChange in scrollable-tab-view. The video component does receive a this.props.tabChanged=true, but that moment seems to be too late to set the video to pause.

Any ideas?

**Comment by skv-headless** [comment]
Hi. What is ```onTabChange```? How it receive ```this.props.tabChanged=true``` I don't know anything about such prop? What do you mean that it is too late?

**Comment by beebase** [comment]
it's actually called onChangeTab which is a property of ScrollableTabView.
I tried triggering my video (child) component with the onChangeTab event.
OnChangeTab event, changes state of ScrollableTabView which I can push downwards to child component(Video), but that doesn't trigger a Video update.

I guess I'm looking for some simple event like onSwipe, onHide or whatever in order to stop my video.
Maybe there's a way to add an event listener to my Video component that detects onHide?

> onChangeTab (Function) - function to call when tab changes, should accept 1 argument which is an Object containing two keys: i: the index of the tab that is selected, ref: the ref of the tab that is selected

**Comment by skv-headless** [comment]
try ```onScroll```. Not sure that I understood when exactly you want to stop video? During transition between tabs?

**Comment by beebase** [comment]
I also tried onScroll without any luck. (maybe my fault)

Anyway, the next solution works very well, using emitter and listener.
Video stops now  when onChangeTab event is triggered.

Main Component, import EventEmitter
```
`var EventEmitter = require('EventEmitter');`
```

Add eventEmitter object before mounting
```
  componentWillMount() {
    this.eventEmitter = new EventEmitter();
  }
```

```
render() {
    return (
      <ScrollableTabView renderTabBar={() => <DefaultTabBar />}
                         style={styles.scroll}
                         tabBarUnderlineColor={COLORS.GREEN}
                         tabBarActiveTextColor={COLORS.GREEN}
                         tabBarInactiveTextColor={COLORS.MID_GREY}
                         tabBarBackgroundColor={COLORS.DARK_GREY}
                         tabBarPosition="top"
                         onChangeTab={this.onTabChange.bind(this)}>
```

Method that's linked to onChangeTab.
```
  onTabChange(e) {
//2nd parameter object only used or logging
    this.eventEmitter.emit('tabChange', { tabName: e.ref.props.tabLabel});
  }
```

Attach eventEmitter to the component 'Demo' inside one of the Tabs
(pushes eventEmitter down to Child Component(s) )
```
<ScrollView tabLabel="Demo"
                    style={styles.tabView}>
          <Demo skill={this.props.skill} events={this.eventEmitter} />
        </ScrollView>
```

Arriving in the bottom VideoComponent
Import Subscribable (to create listeners)
`var Subscribable = require('Subscribable');`

after mounting, add listener that catches the 'tabChange' emit from Main Component
and calls this.stopVideo()
```
    componentDidMount() {
      this.addListenerOn(this.props.events, 'tabChange', this.stopVideo);
    },
```

**Comment by lalzada** [comment]
@beebase how did you stop react-native-video? i don't see any prop or method to pause/play react-native-video? i am done with tabChange things but stuck to pause/play video.

Thanks
