### ISSUE TITLE
Cannot render custom tab

### ISSUE THREAD

**Issue by grabbou** [brentvatne/react-native-scrollable-tab-view#25]
```
'Warning: React.createElement: type should not be null or undefined. It should be a string (for DOM elements) or a ReactClass (for composite components).'
```
and it's blank, even when using given example. Running on 0.8. 

Code:
`<ScrollableTabView renderTabBar={() => <VenueTab />}>...</ScrollableTabView />`

**Comment by brentvatne** [comment]
maybe not causing it but

`</ScrollableTabView />` seems problematic

**Comment by grabbou** [comment]
You saved my life........
