### ISSUE TITLE
Unable to install example

### ISSUE THREAD

**Issue by sasha42** [brentvatne/react-native-scrollable-tab-view#250]
I'm trying to get the example working, but unfortunately I can't seem to get around figuring out how to fix the react dependency:

![screen shot 2016-04-30 at 02 56 24](https://cloud.githubusercontent.com/assets/1775702/14933138/10a926a4-0e85-11e6-85f2-bf3db107d587.png)

If I install react, I keep getting conflicts, and if I remove react, I keep getting errors. I ran npm install and then run-ios, tried a few different versions of node, and yet I still bump into this.

```
├── react@0.14.5 extraneous
├── react-native@0.22.2
├── react-native-scrollable-tab-view@0.4.1
└── react-native-vector-icons@1.3.4
```

**Comment by sasha42** [comment]
I was able to follow the instructions in 'Add it to your project' and 'Basic usage' however. In this instance I was running:

```
├── react@0.14.8
├── react-native@0.24.1
├── react-native-scrollable-tab-view@0.4.1
└── react-native-simple-router@0.9.1
```

**Comment by skv-headless** [comment]
Should be fixed in master. Thanks for issue.
