### ISSUE TITLE
Text going out of section frame

### ISSUE THREAD

**Issue by tnguyen42** [brentvatne/react-native-scrollable-tab-view#26]
Hi,

I didn't see anybody reporting this issue so here it is: I tried the basic usage example that works perfectly fine... Except if the inside text is too long to hold in a section.
Here's what it gives:
![image](https://cloud.githubusercontent.com/assets/12211685/9150283/680fd2e2-3dd1-11e5-8420-d7e8bdd79953.png)

When the code is simply:
```es6
render() {
	 return (
		<View style={styles.container2}>
			<ScrollableTabView>
				<Homepage tabLabel="React" />
				<Profile tabLabel="Flow" />
				<Settings tabLabel="Jest" />
			</ScrollableTabView>
		</View>
	);
}
```
With the Homepage component being defined as follows:
```es6
class Homepage extends Component {
	render() {
		return (
			<View style={styles.container}>
				<Text style={styles.welcome}>
					Welcome! This is the Homepage. And some more ligns just to check everything's fine.
				</Text>
			</View>
		);
	}
}
```

It used to automatically wrap in the Navigator. For info here's styles.container:
```
container: {
	flex: 1,
	justifyContent: 'center',
	alignItems: 'center',
	backgroundColor: '#F5FCFF',
},
```

**Comment by tnguyen42** [comment]
Update: apparently it's the alignItems center the messes everything up. Didn't figure out why yet.

**Comment by brentvatne** [comment]
@tnguyen42 - any updates?

**Comment by tnguyen42** [comment]
Nope sorry, I tried another way so I'm not having this issue anymore.
You can close it if you want, I believe it's kind of uncommon.
