### ISSUE TITLE
Upgrading to 0.9.0 breaks the CustomTabBar

### ISSUE THREAD

**Issue by pickhardt** [brentvatne/react-native-scrollable-tab-view#29]
For some reason, the styles on the CustomTabBar break when upgrading form 0.8.0 to 0.9.0. It has to do with the flex not taking up equal space. I've just double checked, because I know it sounds weird, but the only thing changed is the version of RN.

See screenshots:

0.9.0
![screen shot 2015-08-18 at 11 27 20 am](https://cloud.githubusercontent.com/assets/610082/9338926/407438c2-459c-11e5-8bb6-be1800c63ab4.png)

0.8.0, with equal spacing
![screen shot 2015-08-18 at 11 24 50 am](https://cloud.githubusercontent.com/assets/610082/9338928/41ef3e4a-459c-11e5-9967-ead27390359d.png)

Any idea?

**Comment by ranyefet** [comment]
+1 
I got the same error in 0.9.0
Anyone has a fix? it looks like flex properties has no effect.

**Comment by pickhardt** [comment]
Not me, not yet... I tried for a decent amount of time too. I'm not sure why it would break just by upgrading to 0.9.0 but I downgraded and it fixed it, then upgraded and it broke it, so I'm pretty confident that just upgrading is what broke it.

**Comment by tnguyen42** [comment]
Try to replace your tab style by:
```es6
  tab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 10,
    width: deviceWidth / numberOfTabs,
  },
```

**Comment by ranyefet** [comment]
@tnguyen42 Thanks for the suggestion. But I rather let Flex do it's thing instead of using fixed width.
Anybody know why Flex properties has no affect?

**Comment by tnguyen42** [comment]
If you're using @pickhardt design, the bottom bar width is already defined depending on the deviceWidth and the numberOfTabs.
Otherwise, no clue why flex properties aren't working.

**Comment by cjmling** [comment]
I upgraded to 0.10.0 and having the same issue. Thanks @tnguyen42  for quick fix for now :)

**Comment by brentvatne** [comment]
Thanks @christopherdro for the fix :)

**Comment by christopherdro** [comment]
:+1:
