### ISSUE TITLE
Tab horizontal scroll overrides SliderIOS

### ISSUE THREAD

**Issue by anthony-liddle** [brentvatne/react-native-scrollable-tab-view#3]
I have the SliderIOS included in one of my views, and dragging the slider fires the scrollable tab view, making it impossible to move the slider handle.

**Comment by brentvatne** [comment]
Good point @anthony-liddle! I was a little greedy in taking the responder status anytime you swipe horizontally, so I went ahead and changed this so this component only takes over your swipe if you start it within `edgeHitWidth` px of the edges of your screen - this defaults to 30px, which is the iOS default for swiping back and same as what is used for the `Navigator` gestures. If you upgrade to `0.1.7` it should just work and you can configure that setting via the `edgeHitWidth` prop: https://github.com/brentvatne/react-native-scrollable-tab-view#props

**Comment by anthony-liddle** [comment]
You, sir, are awesome. Thank you!

**Comment by brendan-rius** [comment]
Is the fix still working?
