### ISSUE TITLE
Can the default bar be styled ?

### ISSUE THREAD

**Issue by cjmling** [brentvatne/react-native-scrollable-tab-view#30]
Just want to customize the padding, backgroundColor and border. Just putting and styling tab and tabs doesn't seems to work.  Or it can be only achieved through customBar ?

**Comment by tnguyen42** [comment]
Customizing it from the customTabBar works fine for me.

**Comment by cjmling** [comment]
@tnguyen42  you mean , i have to create customTabBar in order to style it ?

**Comment by tnguyen42** [comment]
That's right, and then you have to reference it like this:
```
var CustomTabBar = require('./customTabBar');

<ScrollableTabView renderTabBar={() => <CustomTabBar />} >
```

**Comment by cjmling** [comment]
Thanks alot @tnguyen42  it work as expected :)
