### ISSUE TITLE
[Packager] Unable to resolve module precomputeStyle

### ISSUE THREAD

**Issue by alejomendoza** [brentvatne/react-native-scrollable-tab-view#31]
I found this issue, I'm running react-native 0.8.0. My app runs in development and the packager throws that error. When I set the app for production mode (minifying the js and running it inside the app) it crashes.

**Comment by tnguyen42** [comment]
I have the same unresolved module with 0.9 when running the app:

```
Unable to resolve module precomputeStyle from /App/node_modules/react-native-scrollable-tab-view/DefaultTabBar.js
Unable to resolve module precomputeStyle from /App/node_modules/react-native-scrollable-tab-view/index.js
```

I simply got it installed in a new project.

**Comment by tnguyen42** [comment]
Hi,
Not a major issue I think, but nothing new? ^^

**Comment by estahn** [comment]
@tnguyen42 How do you fix it?

**Comment by lionrock** [comment]
I got this issue too, I'am using react-native 0.11.2, and when I start my App terminal throws this error
<pre>
Unable to resolve module precomputeStyle from /Users/leo/Desktop/anlint-react/node_modules/react-native-scrollable-tab-view/index.js

Unable to resolve module precomputeStyle from /Users/leo/Desktop/anlint-react/node_modules/react-native-scrollable-tab-view/DefaultTabBar.js
</pre>

**Comment by MossP** [comment]
+1
I've also just installed this to a new project and getting this error.
RN 0.14.2
Node v5.0.0

Has anyone managed to fix it?

**Comment by qudao** [comment]
precomputeStyle is not supported anymore.

**Comment by iominh** [comment]
It looks like the 0.2.2-alpha version fixes this by not using precomputeStyle, so I got around this error by using the newer version with RN 0.13.2 and Node 4.0.0:

```javascript
npm install react-native-scrollable-tab-view@0.2.2-alpha --save
```
