### ISSUE TITLE
Ability to place tab view in the middle of the frame?

### ISSUE THREAD

**Issue by robtg4** [brentvatne/react-native-scrollable-tab-view#34]
This is not really an issue as much as an inquiry - are you able to place the tab view in the middle of the screen? Much like we see below:

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/13613075/9703765/9fe9fa3a-545b-11e5-9fd1-46d0c4c266ba.gif)

Currently I have this:

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/13613075/9716705/63aa2d94-553a-11e5-9bad-c5155c5e3006.gif)

**Comment by skv-headless** [comment]
I don't see a problem to do it. Is it steel an issue?
