### ISSUE TITLE
[Crash] The app crashes when scrolling and inside a tab & switching tab at the same time

### ISSUE THREAD

**Issue by JonathanWi** [brentvatne/react-native-scrollable-tab-view#36]
I have 3 tabs, all of them ListView. If I try to switch tab while scrolling, I'll have a very laggy animation, up to the point where it crashes. This has been tested and reproduced on an iPhone 6 & iPhone 5.

Any idea? Should we delegate a stopScroll when switching tab?

Thanks

**Comment by brentvatne** [comment]
This should be fixed in 0.3.0 :)
