### ISSUE TITLE
Great job! But not smooth in android. Come on!

### ISSUE THREAD

**Issue by bullda** [brentvatne/react-native-scrollable-tab-view#37]

**Comment by brentvatne** [comment]
Come on! :smile:

**Comment by ide** [comment]
@bullda excited for your PR!

**Comment by jbrodriguez** [comment]
@brentvatne it is slow on Android.

It does seem though, that the underlying Animation component is still not optimized for Android.

**Comment by jbrodriguez** [comment]
I created a custom tabbar, added justifyContainer: 'space-between' to the tabs styles and it's pretty smooth now.

**Comment by brentvatne** [comment]
@jbrodriguez - nice! well done

**Comment by kinhunt** [comment]
@jbrodriguez , cool, reminder of a typo, it should be justifyContent

**Comment by joacodeviaje** [comment]
Do you guys consider this done with the justifyContent fix? I still get the transitions very slow.

I am looking for a solution, if I came with something I'll let you know.

Thanks for the awesome component!

**Comment by brentvatne** [comment]
Should be good on Android now because it is using ViewPagerAndroid! Check out 0.3.0
