### ISSUE TITLE
title not align center

### ISSUE THREAD

**Issue by py110** [brentvatne/react-native-scrollable-tab-view#38]
![image](https://cloud.githubusercontent.com/assets/13548241/9906065/0ab99868-5cbb-11e5-9e8b-2575316f52c7.png)
 <ScrollableTabView  >
                    <ScrollView tabLabel="ion|ios-paper" style={styles.tabView}>
                        <View style={styles.card}>
                            <Text>News</Text>
                        </View>
                    </ScrollView>
                    <ScrollView tabLabel="ion|person-stalker" style={styles.tabView}>
                        <View style={styles.card}>
                            <Text>Friends</Text>
                        </View>
                    </ScrollView>

                </ScrollableTabView>

**Comment by eyaleizenberg** [comment]
Same issue here

**Comment by fomahaut** [comment]
It because `TouchableX` changed at React-Native [0.9.0](https://github.com/facebook/react-native/releases/tag/v0.9.0-rc). Please see #29 

update
```jsx
<TouchableOpacity key={name} onPress={() => this.props.goToPage(page)}>
        <View style={[styles.tab]}>
          ...
        </View>
</TouchableOpacity>
```
to
```jsx
<TouchableOpacity key={name} onPress={() => this.props.goToPage(page)}  style={[styles.tab]}>
          ...
</TouchableOpacity>
```
will solve it.

**Comment by brentvatne** [comment]
Great, can someone submit a PR to fix this if it's still broken? I haven't had much of a chance to look at this project recently

**Comment by fomahaut** [comment]
@brentvatne I submited a PR for this, please take a look. Feel free to tell me if I did something bad.

**Comment by webwelten** [comment]
Hey, can you provide a version with the layout fix in the repo? Would have done it myself but was not sure how you plan to integrate it.

**Comment by brentvatne** [comment]
@webwelten - it's in 0.3.0 now!
