### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by michalraska** [brentvatne/react-native-scrollable-tab-view#4]
In landscape mode has children still the same width and tab at left side is partially displayed too.

![screen shot 2015-06-25 at 15 10 04](https://cloud.githubusercontent.com/assets/827753/8354946/5ba57e6e-1b4c-11e5-9152-9705020860db.png)

**Comment by brentvatne** [comment]
Hi @michalraska - I haven't made this compatible with landscape mode yet - we would need to update the `deviceWidth` when we rotate the device, if you have time to submit a pull request for that it would be much appreciated!

**Comment by michalraska** [comment]
Is currently possible to somehow find out orientation (landscape | portrait) of device now? If no, would be ok to create another dependency on: https://github.com/pjjanak/react-native-viewport?

**Comment by brentvatne** [comment]
@michalraska - I'm okay with adding that dependency!

**Comment by michalraska** [comment]
I'm sorry but I find out I don't need scrollable tabs be cause it does not play good with touchables in list view. Maybe later I will try to fix it.

**Comment by brentvatne** [comment]
Sure @michalraska :smile:

One thing you might want to look at is the recently added `edgeHitWidth` which would allow this lib to place better with touchables in list view.

**Comment by DrMabuse23** [comment]
https://github.com/DrMabuse23/react-native-device-orientation maybe this helps you out trigger on orientation change

**Comment by avindra** [comment]
This is actually a pretty important one. Has anyone taken the issue yet?

**Comment by brentvatne** [comment]
@avindra - I don't think so, if you get a chance to look into it that would be appreciated

**Comment by ronnpang1** [comment]
Has this issue been fixed? I'm still hitting this problem
