### ISSUE TITLE
I want to put the tab in the bottom what should I do, if i modify your code.

### ISSUE THREAD

**Issue by YComputer** [brentvatne/react-native-scrollable-tab-view#41]
I want to put the tab in the bottom what should I do, if i modify your code.
thanks.

**Comment by YComputer** [comment]
I found the way.
change the render order source in ScrollableTabView's render() methed.

**Comment by kinhunt** [comment]
nice try

**Comment by NixusCN** [comment]
@YComputer How to do ? Where is the render order source that you said ? I don't find it.

**Comment by NixusCN** [comment]
@YComputer Thanks. I had found it. 谢谢，我已经找到了

**Comment by yahue** [comment]
@NixusCN 你是在哪里找到的呀 有代码示例吗？

**Comment by xQuotes** [comment]
@yahue <ScrollableTabView initialPage={2}
        renderTabBar={() => <Tabs />}
        tabBarPosition="bottom">

**Comment by xQuotes** [comment]
@yahue

**Comment by xQuotes** [comment]
@yahue `<ScrollableTabView initialPage={2} renderTabBar={() => <Tabs />}  tabBarPosition="bottom">`
