### ISSUE TITLE
Appears broken in RN 0.12 (RE: precomputeStyle)

### ISSUE THREAD

**Issue by tolu360** [brentvatne/react-native-scrollable-tab-view#46]
I'm using a CustomTabBar but it appears properties of objects passed to the `precomputeStyle` function all return undefined when I upgraded to RN 0.12. Passing same object directly to `setNativeProps` seems to work but then the tabs do not change when tapped.

**Comment by sunnylqm** [comment]
see https://github.com/facebook/react-native/issues/2999

**Comment by tolu360** [comment]
Thanks for pointing that out @sunnylqm - you are right.

**Comment by sulliwane** [comment]
Cant' find how to fix this bug (even looking at the 2999 bug) Could you be more specific? Thank you very much.

![precompute](https://cloud.githubusercontent.com/assets/1733686/10598727/01544682-772e-11e5-8949-1bb25c95d5c3.png)
undefined is not an object (evaluating 'validAttributes[key]')

**Comment by sunnylqm** [comment]
find 'precomputeStyle.js'(search it under node_modules/react-native), at line 66:
change the following:
  var process = validAttributes[key] && validAttributes[key].process;
to:
  var process = validAttributes && validAttributes[key] && validAttributes[key].process;

Yes, it's a bug. So this is just a temp workaround. The final solution is to wait both react-native and scrollable-tab-view to update.

**Comment by buhe** [comment]
+1

**Comment by sulliwane** [comment]
Ok, got it! It works now, thanks a lot.

**Comment by brentvatne** [comment]
Can someone submit a pull request to fix this please? :)

**Comment by sunnylqm** [comment]
@brentvatne   
Actually, the latest github master version doesn't have the problem...well, isn't this your repo and you forget to publish it to npm?...

**Comment by josmardias** [comment]
It's published on 0.2.1-alpha and 0.2.2-alpha.

**Comment by brentvatne** [comment]
Published in 0.3.0 now
