### ISSUE TITLE
This doesn't work on 0.12 ?

### ISSUE THREAD

**Issue by cjmling** [brentvatne/react-native-scrollable-tab-view#47]
The tab doesn't seems to style and nor the swipable.  It does able to tab on each and tabbed move

**Comment by cjmling** [comment]
Ok it doesn't work because using 
```npm install react-native-scrollable-tab-view --save``` 

install 0.1.10 version.

While you already fixed the layout problem in alpha version. But the swipe feature doesn't seems to work yet.

btw. it kinda slow/lag comparing to iOS

**Comment by cjmling** [comment]
For swipe to work i have to swipe right from edge of the screen. I wanted to swipe from which ever point. got to change value  ```edgeHitWidth:```  in index.js  . I changed to 150 and work as expected.  

But yeah if possible, if this could be little more smoother. it kinda lag and slow :'(

**Comment by stylesuxx** [comment]
The *edgeHitWidth* may be passed as a prop to the *ScrollableTabView* component, you do not need to hard code that ;-)

**Comment by skv-headless** [comment]
@cjmling check latest version please. I hope it is better.
