### ISSUE TITLE
Sticky ListView SectionHeaders disappear on tab switch

### ISSUE THREAD

**Issue by syousif94** [brentvatne/react-native-scrollable-tab-view#5]
![ios_simulator_screen_shot_jun_26__2015__7_12_19_am](https://cloud.githubusercontent.com/assets/8747517/8379244/80dbf9a6-1bd3-11e5-8ed7-df3e972c9937.png)

**Comment by syousif94** [comment]
upon further experimentation it appears that setting removeClippedSubviews on a list view causes this

**Comment by brentvatne** [comment]
@syousif94 - interesting! could you post a code example with the bug and with the fix? Would be awesome to add to the README!
