### ISSUE TITLE
0.13 new bugs

### ISSUE THREAD

**Issue by marsprince** [brentvatne/react-native-scrollable-tab-view#50]
In RN 0.13, facebook removed precomputeStyle,you should remove precomputeStyle and replace all codes
like 
```sh
this.scrollView.setNativeProps(precomputeStyle{
          transform: [{translateX: -1 * offsetX}],
        });
```
by
```sh
this.scrollView.setNativeProps({style:{
          transform: [{translateX: -1 * offsetX}],
        }});
```

**Comment by brentvatne** [comment]
thanks! could you possible submit a PR for this?

**Comment by syarul** [comment]
+1 PR

**Comment by marsprince** [comment]
sorry,I forgot it.The codes in github was different from codes in npmjs and I used an old version.It will be right If you update it in npmjs.

**Comment by Yancy729559** [comment]
IN  RN 0.14  “this.refs[TAB_UNDERLINE_REF].setNativeProps({style{
      left: (deviceWidth * value) / this.props.tabs.length
    }})” error
