### ISSUE TITLE
undefined is not an object ( evaluating 'Dimensions.get') -> on Android

### ISSUE THREAD

**Issue by BigPun86** [brentvatne/react-native-scrollable-tab-view#52]
Hey there. I am trying to use your Component, unfortunately i get this error, and i am not sure how to solve this... Anyone with same issues?

Best Regards

**Comment by stylesuxx** [comment]
I am also playing around with this component on Android - did not run into any problems regarding the Dimensions. Maybe you can tell us more about how you are using it, or with which example this is happening?

**Comment by BigPun86** [comment]
I simply tried the basic usage and injection of a custom bar which is shown in the readme. Now this is how my code looks like:

    'use strict';
    var React = require ('react-native');
    var {AppRegistry, StyleSheet, Text,View,Image, TouchableHighlight, Platform} = React;
    var ScrollableTabView = require ('react-native-scrollable-tab-view');
    var CustomTabBar      = require ('../CustomTabBar');

    var TabBarControllerAndroid = React.createClass({

    render: function () {
         var Page1 = require ('././Page1');
         var Page2    = require ('././Page2');*/
        var Page3 = require ('././Page3');

        return (
            <ScrollableTabView renderTabBar={() => <CustomTabBar someProp={'here'} />}>
                <Page1 tabLabel="News"/>
                <Page2 tabLabel="PickUp"/>
                <Page3 tabLabel="More"/>
            </ScrollableTabView>
        );
     }
    });

    module.exports = TabBarControllerAndroid;


The error comes in the line where i require ScrollableTabView. 


My TabPages are simple Views with Text elements.

And my packager outputs these lines:

Unable to resolve module precomputeStyle from .../node_modules/react-native-scrollable-tab-view/index.js
Unable to resolve module Dimensions from .../node_modules/react-native-scrollable-tab-view/DefaultTabBar.js
Unable to resolve module precomputeStyle from .../node_modules/react-native-scrollable-tab-view/DefaultTabBar.js

**Comment by stylesuxx** [comment]
Did you install via *npm* or clone the repository directly into your node modules directory?

**Comment by BigPun86** [comment]
I installed it via npm. I don´t get the this error anymore, after setting up my whole project new. But unfortunately i get a new error message --> undefined is not an object (evaluating 'validAttributes[key]')
i created a new issue for this.

My thought were maybe, but i just don´t know how this could affect it, is that i have used the react-native-router to navigate through my app, now i am using simple navigator.

**Comment by stylesuxx** [comment]
Well, I had my problems with the *npm* version (I *think* it was the same error you made a new issue for), so I directly cloned the repo to my *node_modules* folder installed the dependencies and use the current master branch - maybe this is something you should try.

If you can confirm that it works better, maybe we can get @brentvatne to publish a new version ;-)

**Comment by BigPun86** [comment]
Hell yeah! It worked thanks mate @stylesuxx !

**Comment by brentvatne** [comment]
Removed rebound dependency, published 0.3.1!
