### ISSUE TITLE
Spring props not working

### ISSUE THREAD

**Issue by stylesuxx** [brentvatne/react-native-scrollable-tab-view#53]
The props for spring tension, friction and clamp are being ignored.
In the *goToPage* method friction and tension are passed hard coded to *Animated.spring*

Also I think you are not using *rebound* anymore, instead *Animated.spring* which only supports friction and tension if I am not mistaken. This also means *rebound* could be removed as a dependency and the *clampSpring* prop should be removed from the *Readme*.

If you want I can submit a PR - just let me know if I am talking BS above ;-)

**Comment by brentvatne** [comment]
Looks like that's merged now :)
