### ISSUE TITLE
[Android 5.0] Trying to call navigator.push but the screen freezes for 1 second.

### ISSUE THREAD

**Issue by han4wluc** [brentvatne/react-native-scrollable-tab-view#54]
I can replicate this on any Android 5.0 device. No problem with iOS or Android 4.4.

I have my <ScrollableTabView> Inside a Navigator.  I am passing the navigator to one the tabs with `<Tab rootNavigator={rootNavigator}> ... </Tab>`. Then I try to call `rootNavigator.push` from TabOne, but there is a 1 second delay before the view starts to change. This is not a onPress problem.

Inside TabOne.js
```
<TouchableOpacity onPress={this.openArticleView}>
    <Text> Open Article View </Text>
</TouchableOpacity>
...
openArticleView: function(){
    this.props.rootNavigator.push({
      id: 'ArticleView',
      name: 'name',
    });
}
```
The screen freezes for 1 second before navigator.push starts to take effect.

**Comment by sampurcell93** [comment]
I had a problem exactly like this. It turned out to be a general problem related to console.logging objects - it appears that doing so is expensive in RN and will cause a slight delay. Be sure you are not making any extra console logs in your press stack.

**Comment by skv-headless** [comment]
Try dev=false

**Comment by skv-headless** [comment]
I almost sure that problem not in react-native-scrollable-tab-view. Reopen if you still experience this issue.
