### ISSUE TITLE
[Android] [BUG] Click event wrong tab.

### ISSUE THREAD

**Issue by han4wluc** [brentvatne/react-native-scrollable-tab-view#58]
I am using scrollable-tab-view with 3 children. Each child is a ListView
```
  <ScrollableTabView edgeHitWidth="200">
      
      <View tabLabel="TabOne" style={styles.container}>
        <TabOneListView />
      </View>
      <View tabLabel="TabTwo" style={styles.container}>
        <TabTwoListView />
      </View>
      <View tabLabel="TabThree" style={styles.container}>
        <TabTwoListView />
      </View>
      
  </ScrollableTabView>
```

On TabOne, I click on my list item, the click event is handled,  it opens a new page, it's all ok.
When I click on an item on TabTwo, it HANDLES CLICK EVENTS FROM TAB ONE ...
I can scroll properly in TabTwo, but when I click an item, it's as if it is clicking on TabOne.

Please, can anyone try replicate this issue?

There is no problem with iOS.

**Comment by w2moon** [comment]
me too,just TabOne can be clicked on android.

**Comment by mangogogos** [comment]
+1 touchables from my first tab are taking over touch events that should be going to the second tab

**Comment by syarul** [comment]
Only the first tab working currently, Switching to 2nd ++ pages only render the view but does not translate values correctly, still looking how to solve this

**Comment by maraujop** [comment]
It's my understanding that is not a bug in react-native-scrollable-tab-view but react-native itself. Looks like although in Android everything is moving with the interpolation, gestures get delegated to the first tab, as if the components behind gesture handling hadn't moved, I haven't seen any issue like this one reported in react-native, but @brentvatne is the best one to know this.

**Comment by brentvatne** [comment]
This was a bug with React Native Android, but that was also fixed and also the original problem shouldn't be happening anymore even if it weren't fixed because we aren't translating views anymore but using VIewPagerAndroid instead :) https://github.com/facebook/react-native/pull/3954

**Comment by brentvatne** [comment]
See version 0.3.1 for fix
