### ISSUE TITLE
the latest rn could not run

### ISSUE THREAD

**Issue by PanJiaChen** [brentvatne/react-native-scrollable-tab-view#65]
my rn is "^0.13.2"
when l run 
![image](https://cloud.githubusercontent.com/assets/8121621/10907223/3d3872be-8263-11e5-8fbf-7dd8cbe755de.png)

the Latest release maybe delete precomputeStyle module
https://github.com/facebook/react-native/issues/3760

**Comment by caiiiyua** [comment]
Same issue with rn 0.13.1

**Comment by johnnyjanzen** [comment]
Same issue (0.13.2).  This appears to be due to the deletion of the "precomputeStyle" module from the latest versions of react.  https://github.com/facebook/react-native/issues/3760

**Comment by flyingmate** [comment]
Please fix this...

**Comment by maraujop** [comment]
Meanwhile you can do `npm install brentvatne/react-native-scrollable-tab-view`. Current `master` branch has this fixed, a new version should be released in npm

**Comment by PanJiaChen** [comment]
@maraujop  it work,thx

**Comment by johnnyjanzen** [comment]
Thanks!

**Comment by JonathanWi** [comment]
Hey @maraujop, installing the version you mentioned worked for me, but I now find myself unable to swipe left on the scrollable-tab-view (only right scroll is registered). 

Am I the only one with this issue? It's driving me insane!
