### ISSUE TITLE
How can i hide the Tabs? 

### ISSUE THREAD

**Issue by BigPun86** [brentvatne/react-native-scrollable-tab-view#66]
I tried to set the height Attribute in my CustomTabBar to 0, thought that would hide my Tabs. But it does not work. Is there another way to hide it?

**Comment by josmardias** [comment]
In which version are trying?
Try 0.2.2-alpha, rebase your CustomTabBar on DefaultTabBar.js of the master branch.

**Comment by BigPun86** [comment]
Yeah, i am using 0.0.2-alpha. I rebased it, but nothing changes...Thanks though

**Comment by MossP** [comment]
try 0.1 height. there was a but in RN that caused 0 height items to ignore height. I'm not sure if it's been fix in RN yet.

**Comment by scgough** [comment]
I've just been looking at this (v0.3.4) and I can remove the tabs by creating a custom tabbar and on the render, `return false`

**Comment by gadiel** [comment]
why not use [ViewPagerAndroid] (https://facebook.github.io/react-native/docs/viewpagerandroid.html#content ) directly?

**Comment by skv-headless** [comment]
Guys, thank you for your solutions
