### ISSUE TITLE
cannot scroll ListView inside ScrollableTabView

### ISSUE THREAD

**Issue by yychun1217** [brentvatne/react-native-scrollable-tab-view#67]
I have 3 listViews as children of ScrollableTabView, I could swipe between them, but I cannot scroll them.

Anyone has idea why it is so?

Below is the related code:

render: function() {
    return (
      <ScrollableTabView
        renderTabBar={() => <CustomTabBar />}
        edgeHitWidth={edgeHitWidth}>
            <ProductList
            tabLabel="Selling"
            style={styles.tabView}
            locked={false} />
          <ProductList
            tabLabel="Sold"
            style={styles.tabView}
            locked={false} />
          <ProductList
            tabLabel="Favorite"
            style={styles.tabView}
            locked={false} />
      </ScrollableTabView>
}

Inside ProductList.js

  render: function() {
    var content = this.state.dataSource.getRowCount() === 0 ?
      <View style={styles.centerEmpty}>
        <Text>{this.state.isLoading ? 'loading' : 'empty'}</Text>
      </View> :
      <ListView
        scrollRenderAheadDistanc={600}
        style={styles.listView}
        dataSource={this.state.dataSource}
        renderRow={this._renderRow}
        automaticallyAdjustContentInsets={false}
        keyboardDismissMode="on-drag"
        keyboardShouldPersistTaps={true}
        showsVerticalScrollIndicator={false} />;
    return content;
  }

**Comment by marsprince** [comment]
I think it's not problem of ScrollableTabView .You missed flex:1 in your View Component

**Comment by brentvatne** [comment]
@marsprince seems to be right :)
