### ISSUE TITLE
unkown module "precomputeStyle"

### ISSUE THREAD

**Issue by josmardias** [brentvatne/react-native-scrollable-tab-view#69]
This error happens on both DefaultTabBar.js and index.js on react-native@0.14.1
More information at facebook/react-native/issues/3760

**Comment by MartinTale** [comment]
Just came across the same issue. Any idea when this will be fixed?

**Comment by BigPun86** [comment]
Just update to the newest scrollable-tab-view module. This worked for me. Check your DefaultTabBar with the newest DefaultTabBar from then repository, you will see some differences.

**Comment by josmardias** [comment]
You're right! 
4dbd5c728a1f86ad0e94e4794a989bb8833de8dd

It's not published as a new version yet

**Comment by josmardias** [comment]
Works on 0.2.2-alpha
