### ISSUE TITLE
Tab bar places itself under the navigationbar

### ISSUE THREAD

**Issue by frankbolviken** [brentvatne/react-native-scrollable-tab-view#7]
When implementing this with a navigation bar, the tab bar get's rendering behind the navigation bar.
<img width="381" alt="screen shot 2015-07-03 at 12 30 03" src="https://cloud.githubusercontent.com/assets/688190/8497658/446e1916-217f-11e5-9feb-272371ee2f42.png">
```javascript
render: function() {
    return (
      <NavigatorIOS
        style={styles.container}
        initialRoute={{
          title: 'Mine Rabatter',
          component: Main,
        }}
      />
    );
  }
```

**Comment by brentvatne** [comment]
@frankbolviken - I personally use `Navigator` everywhere [because it's much more customizable](https://facebook.github.io/react-native/docs/navigator-comparison.html#content). I would just wrap this component in a `View` with some paddingTop to push it down accordingly in this case.

**Comment by plrthink** [comment]
@brentvatne I ran into same issue here, you said add some paddingTop to the wrapper `View`, but how t o decide the value of this paddingTop since we don't know height of navigationBar?

**Comment by grabbou** [comment]
Even when using Navigator, you still need to add marginTop manually to top-most view.

**Comment by brentvatne** [comment]
As @grabbou said, add a marginTop ;)
