### ISSUE TITLE
After 0.14 update, my views don´t recognise clicks.

### ISSUE THREAD

**Issue by BigPun86** [brentvatne/react-native-scrollable-tab-view#71]
After i have updated my React-Native to 0.14 which breaks my Scrollable Tab View with four Tabs.
My View components on my tabs 2,3 and 4 don't work anymore. Anybody with same issues after update?

**Comment by BigPun86** [comment]
The weird thing is that i can only interact with the first TabView Component. If i switch to tab 2,3 or 4 and click into the View and than go back to Tab 1 it changed the content of Tab 1. It is like Tab 1 View is always there?!

**Comment by fauxtonic** [comment]
Same problem here even with 0.13. The FacebookTabsExample app shows the same behavior as well. RN 0.9 works but reverting that far back breaks a number of other modules I'm using so not a solution for me anyway.

**Comment by sulliwane** [comment]
I'm using **RN 0.14.2** and **react-native-scrollable-tab-view@0.2.2-alpha**, and I have the exact same problem. On my **Tab N°2**, I can move elements from **Tab N°1**. And I cannot click on the buttons in **Tab N°2** (or sometimes it works with double click, but it's not stable). Any ideas?

@fauxtonic I think the #50 issue is already solved in 0.2.2-alpha, so I'm really not sure it's related...

**Comment by awesomepankaj** [comment]
Can anybody tell me how to solve this issue????

**Comment by sulliwane** [comment]
I just tried **RN 0.15.0-rc**, and still same problem on Android (only, works perfectly on iOS). Don't know where to start to debug it.

**Comment by BigPun86** [comment]
Still no Fix? This Module was so great until RN12, but sadly this issue won´t be fixed :(

**Comment by iwater** [comment]
same problem on 0.15 android (only, works perfectly on iOS) react-native-scrollable-tab-view@0.2.2-alpha

**Comment by Deadlysmile** [comment]
this issue related to https://github.com/facebook/react-native/issues/3557 and seems already fixed.

**Comment by brentvatne** [comment]
This is fixed in 0.3.1 of react-native-scrollable-tab-view!

**Comment by sulliwane** [comment]
@brentvatne  awsome, thanks!
