### ISSUE TITLE
this.props.children is assumed to be an array but sometimes it isn't

### ISSUE THREAD

**Issue by ippa** [brentvatne/react-native-scrollable-tab-view#72]
Hi, 

Thanks for a great plugin! While evaluating it I ran into a gotcha that probably is very easy to fix. I had some code like this:

```
<ScrollableTabView>
  <View tabLabel={"test"}> bla bla </View>
</ScrollableTabView>
```

Simplest possible start to render something right? but it kept crashing. I pinned it down to a call to ```this.props.children.map``` @ line ~113 in index.js. But this.props.children wasn't an array when there was only 1 child.

So maybe a forced ```Array(this.props.children).map``` would spare this crash from others?

**Comment by sophiaWang611** [comment]
i got the same issue! maybe caused by react-native version. when RN version is bigger than 0.9.0, this component will be broken

**Comment by skv-headless** [comment]
fixed here https://github.com/brentvatne/react-native-scrollable-tab-view/commit/2c5e05cdb7f25ff27df42e782a27a89010188602
