### ISSUE TITLE
clampSpring prop doesn't do anything

### ISSUE THREAD

**Issue by ippa** [brentvatne/react-native-scrollable-tab-view#73]
While experimenting with ScrollableTabView props to mimick the feel of googles youtube app I tried out a low ```springFriction``` (to try to make tabs "flickable") and ```clampSpring={false}``` to make it oscillate around the new selected tab I noticed that ```clampSpring``` doesn't do what the readme says it should do.

I also come up emptyhanded trying to grep the code for references to ```clampSpring```

Is it supposed to work or is the readme wrong? Can you with the current version recommend settings to make the tabs feel like the tabs in the youtube app.

I'm like you in this regard, this is one of my favorite navigation patterns! But we don't want our apps to end up in uncanny walley :). Google have the perfect tab-feel in their apps.

**Comment by ippa** [comment]
I came closer to the youtube-app-feeling with a huge ```edgeHitWidth={1000}``` ... (while having springTension=100 and springFriction=10) but I will wonder about the clampSpring-prop.

**Comment by skv-headless** [comment]
@ippa it is deprecated properties. Please check new version.
