### ISSUE TITLE
None of the props work for me, except of renderTabBar

### ISSUE THREAD

**Issue by BigPun86** [brentvatne/react-native-scrollable-tab-view#74]
I am trying to use especially the locked props, so the only way to switch between the tabs is by tabbing the tabs. But unfortunately the only props which works is the renderTabBar prop.

      <ScrollableTabView
                locked={true}
                ..........tried all other props
                renderTabBar={() => <CustomTabBar someProp={'here'}/>}>
                <View style={styles.tabView} tabLabel="Tab1">
                    <SomeView1 />
                </View>
                <View style={styles.tabView} tabLabel="Tab2">
                    <SomeView2 />
                </View>
      </ScrollableTabView>

Did anybody face the same problem?

**Comment by sulliwane** [comment]
I have the same problem, adding ```"locked={true}"``` do not lock the scrolling, and I can't find any mention of this prop into the code. Is it deprecated? Or any idea why this prop is not working? Thank you.

**Comment by brentvatne** [comment]
Are you on Android? @sulliwane

**Comment by brentvatne** [comment]
This could be broken since we use ScrollView / ViewPagerAndroid now, cc @skv-headless

**Comment by sulliwane** [comment]
@brentvatne yes I'm on Android (and ios), same problem. I just looked at the code, and most of the props are not used anymore. I will PR after ensuring the modifications is cross platform.

**Comment by skv-headless** [comment]
mini roadmap

- update docs, remove unused props
- clean up code, remove unused props

I can do it on this week but not sure exactly when. @sulliwane if you do it would be awesome.

**Comment by sulliwane** [comment]
@skv-headless thanks!!
