### ISSUE TITLE
Anomalous Padding

### ISSUE THREAD

**Issue by brianjd** [brentvatne/react-native-scrollable-tab-view#78]
Hi, having an odd issue with what I'll call "anomalous padding".  I have several tabs, two of the tabs (adjacent) are  a component that returns a scrollview(vertical), with no explicit style applied.  The issue is that the first tab of the two always adds "padding " to the top, while the second displays as expected without any "padding".  Using the inspector both appear identical in terms of x/y/padding/etc.  This is further confirmed by an animation I ran in both, where the calculated animation in the problem tab is thrown off by the obviously incorrect values. I'm attaching images of both tabs scrolled to the top, notice the verticalScrollIndicators.  Any pointers?

![tab1](https://cloud.githubusercontent.com/assets/587461/11381157/39b08f44-92af-11e5-8688-3576d1928848.png)
![tab2](https://cloud.githubusercontent.com/assets/587461/11381158/3db6518c-92af-11e5-9a52-fd48748111f9.png)

**Comment by brentvatne** [comment]
@brianjd - did you end up figuring this out?

**Comment by brianjd** [comment]
@brentvatne - though it felt as if something obvious was being missed, I haven't resolved yet, but I haven't invested any more time since the original post.  But in addition, if I remove the first tab, the second tab (the new first tab) exhibits the same behaviour.  I find this all odd since the parent is just a long horizontal view.

**Comment by mikkoj** [comment]
Had the same problem with a `ListView` inside each tab. Fixed it by setting `automaticallyAdjustContentInsets` to `false` and then manually adjusting `contentInset` to handle a TabBar on the bottom :smile:

**Comment by brianjd** [comment]
@mikkoj Thanks!

**Comment by mauriciord** [comment]
Did you find any solution ?
Same problem here
