### ISSUE TITLE
Any way to listen for when the current page changes?

### ISSUE THREAD

**Issue by eljago** [brentvatne/react-native-scrollable-tab-view#8]
Hello, thank you for this module I really like it.

I want to load the data of a page only when it becomes active.
I'm a little noob with react still so I don't know if this is easy or not to implement, but is there a way to know when a page changes?

Thank you.

**Comment by brentvatne** [comment]
Hey @eljago! I had an undocumented hook for this: `onChangeTab` prop - I added some documentation for it now: https://github.com/brentvatne/react-native-scrollable-tab-view#props - let me know if this works for you as you expect!

**Comment by eljago** [comment]
Worked perfectly, thanks !
