### ISSUE TITLE
how to solve the conflict with SliderIOS

### ISSUE THREAD

**Issue by jxintang** [brentvatne/react-native-scrollable-tab-view#80]
how to solve the problem with left-right swip gesture conflict,except shorten the edgeHitWidth value?

**Comment by brentvatne** [comment]
This should be better now with that we are using ScrollView / ViewPager, let me know if that doesn't fix your problem! Version 0.3.1

**Comment by brendan-rius** [comment]
I have the problem with 0.7.0
