### ISSUE TITLE
RN v0.16.0 Warning: Each child in an array or iterator should have unique "key" prop.

### ISSUE THREAD

**Issue by sulliwane** [brentvatne/react-native-scrollable-tab-view#86]
![scrollableview](https://cloud.githubusercontent.com/assets/1733686/11622760/00edfa12-9d03-11e5-91f4-594f79c08226.jpg)

**Comment by sulliwane** [comment]
just adding a ref to child component solved this issue.

**Comment by sulliwane** [comment]
sorry, I reopen as it was not related to ref.

**Comment by brentvatne** [comment]
@sulliwane - if you add a unique `key`, so `key={thing.id}` for example, to each of the child components that will fix this

**Comment by mangogogos** [comment]
@brentvatne if I understand correctly I should have

    <ScrollableTabView ...props>`
    <Component tabLabel="label 1" key={ thing1.id }/>`
    <Component tabLabel="label 2" key={ thing2.id }/>`
    </ScrollableTabView>`

but this doesn't fix the key warning for me since the key needs to be applied to the containing view.
for now I've modified this repo's index.js to add the tabLabel and the mapping index as a key

**Comment by brentvatne** [comment]
that seems reasonable, can you submit a pr @mangogogos?
