### ISSUE TITLE
Consider updating state of currentPage onscrolling

### ISSUE THREAD

**Issue by vivasonico** [brentvatne/react-native-scrollable-tab-view#87]
I have noticed that when you navigate by pressing the icons in the tab bar the function goto updates the currentPage. However, when scrolling this does not happen. It can be fixed by adding the following line to the _updateScrollValue method:

this.setState({currentPage:Math.round(value)})
```javascript
  _updateScrollValue(value) {
    this.state.scrollValue.setValue(value);
   this.setState({currentPage:Math.round(value)})
}

**Comment by skv-headless** [comment]
_updateScrollValue called often. If I understand how react works correct than it cause unnecessary calculations. I suppose to use https://facebook.github.io/react-native/docs/viewpagerandroid.html#onpageselected for androud and ```onMomentumScrollEnd``` for ios.

**Comment by brentvatne** [comment]
Done, check this out: https://github.com/brentvatne/react-native-scrollable-tab-view/commit/a10437d8b70369f9c81945b4a88077e4edf529e6
