### ISSUE TITLE
Using with react-native-router is slow

### ISSUE THREAD

**Issue by steve-ng** [brentvatne/react-native-scrollable-tab-view#9]
Hi anyone using react-native-router?

I tried to go to different route from the tabbed view and noticed that the animation is quite laggy. Anyone else facing this too?

**Comment by steve-ng** [comment]
it will lag if you rendered a long list. a way to fix this would be to use listView which optimised the rendering

**Comment by brentvatne** [comment]
Nice, thanks for the follow up @steve-ng! :smile: Definitely `ListView` is best to use for long lists
