### ISSUE TITLE
Unable to run example on Android and React 0.16

### ISSUE THREAD

**Issue by DanielHoffmann** [brentvatne/react-native-scrollable-tab-view#90]
The tabs work if I remove the `renderTabBar={() => <FacebookTabBar />` call, but if I leave it in I get the following error:
`Invariant Violation: Element type is invalid:
expected string (for built-in component) or class/function (for composite components) but got: object. Check render method of 'UnimplementedView``

Besides that I am also getting a warning (2 times) when I don't put that renderTabBar prop in:
`Each child in array or iterator should have unique 'key` prop. Check the render method of ScrollableTabView ...`

Tested on Android 5.1 and React 0.16

**Comment by DanielHoffmann** [comment]
Ok the problem was that the example dependency (react-native-icons) required to be registered in the Java code, but I am still getting the warnings.

**Comment by skv-headless** [comment]
@DanielHoffmann if it for android it fixed here https://github.com/brentvatne/react-native-scrollable-tab-view/pull/89 could you check out new version?

**Comment by DanielHoffmann** [comment]
@skv-headless yes it fixed it thanks, but there is no new version with that bugfix yet. 0.3.2 doesn't have it.

I am closing this issue, but it might be a good idea to remove the react-native-icons dependency from the example because it needs to be registered in Java code, more people will probably have the same problem as me.
