### ISSUE TITLE
onChangeTab being not called when scrolling

### ISSUE THREAD

**Issue by eljago** [brentvatne/react-native-scrollable-tab-view#96]
Hello!. I tried it on Android, and noticed that the onChangeTab event is called only when tapping the tab item, and not when the tab changes by scrolling horizontally.
Is how it is intended? How could I make the ScrollableTabView call the onChangeTab event when the page changes by swiping?

**Comment by marsprince** [comment]
The lastest code in github is already fixed.

**Comment by eljago** [comment]
Whoops. Thanks and sorry about that.
